In [14]:
import pandas as pd
import os
import requests

In [15]:
df = pd.read_csv("/Users/DELL/OneDrive/Documents/FaceDetection/face-nationality-dataset-master/links.tsv", sep="\t", dtype=str, quoting=3)

In [16]:
df.head(10)

,id,label,nationality,date_of_birth,year_of_birth,image
0,Q261019,Isabelle Boulay,canada,1972-07-06T00:00:00Z,1972,https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Isabelle_Boulay.jpg/200px-Isabelle_Boulay.jpg
1,Q261049,Florencia Peña,argentina,1974-11-07T00:00:00Z,1974,https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Florencia_Peña.jpg/200px-Florencia_Peña.jpg
2,Q261064,Colin Fleming,united_kingdom,1984-08-13T00:00:00Z,1984,https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Colin_Fleming_2013.jpg/200px-Colin_Fleming_2013.jpg
3,Q261069,Stig Inge Bjørnebye,norway,1969-12-11T00:00:00Z,1969,https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Stig_inge_bjornebye.png/200px-Stig_inge_bjornebye.png
4,Q261123,Alireza Haghi,iran,1979-02-08T00:00:00Z,1979,https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Alireza_Haghi_IRI_(8596887893).jpg/200px-Alireza_Haghi_IRI_(8596887893).jpg
5,Q261361,Netti Witziers-Timmer,kingdom_of_the_netherlands,1923-07-22T00:00:00Z,1923,https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Nettie_Witziers-Timmer.jpg/200px-Nettie_Witziers-Timmer.jpg
6,Q261517,Anne Osborn Krueger,united_states_of_america,1934-02-12T00:00:00Z,1934,https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Anne_O._Krueger_(2004).jpg/200px-Anne_O._Krueger_(2004).jpg
7,Q261526,Meg Foster,united_states_of_america,1948-05-10T00:00:00Z,1948,https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Meg_Foster_Phoenix_Film_Festival_2013.jpg/200px-Meg_Foster_Phoenix_Film_Festival_2013.jpg
8,Q261702,Sunia Koto,new_zealand,1980-04-15T00:00:00Z,1980,https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Sunia_Koto_2007_(cropped).jpg/200px-Sunia_Koto_2007_(cropped).jpg
9,Q261762,Aleka Papariga,greece,1945-11-05T00:00:00Z,1945,https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Aleka_Papariga.jpg/200px-Aleka_Papariga.jpg

In [17]:
pd.set_option('display.max_colwidth', None)

In [18]:
df["image"].head(10)

0                                                https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Isabelle_Boulay.jpg/200px-Isabelle_Boulay.jpg
1                                                  https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Florencia_Peña.jpg/200px-Florencia_Peña.jpg
2                                          https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Colin_Fleming_2013.jpg/200px-Colin_Fleming_2013.jpg
3                                        https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Stig_inge_bjornebye.png/200px-Stig_inge_bjornebye.png
4                  https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Alireza_Haghi_IRI_(8596887893).jpg/200px-Alireza_Haghi_IRI_(8596887893).jpg
5                                  https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Nettie_Witziers-Timmer.jpg/200px-Nettie_Witziers-Timmer.jpg
6                                  https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Anne_O._Krueger_(2004).jpg/200px-Anne_O._Krueger_(2004).jpg
7    https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Meg_Foster_Phoenix_Film_Festival_2013.jpg/200px-Meg_Foster_Phoenix_Film_Festival_2013.jpg
8                            https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Sunia_Koto_2007_(cropped).jpg/200px-Sunia_Koto_2007_(cropped).jpg
9                                                  https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Aleka_Papariga.jpg/200px-Aleka_Papariga.jpg
Name: image, dtype: object

In [19]:
len(df["nationality"].unique())

405

In [20]:
df["nationality"].unique()

array(['canada', 'argentina', 'united_kingdom', 'norway', 'iran',
       'kingdom_of_the_netherlands', 'united_states_of_america',
       'new_zealand', 'greece', 'sweden', 'germany', 'russia', 'estonia',
       'ukraine', 'nigeria', 'jamaica', 'venezuela', 'denmark',
       'switzerland', 'finland', 'france', 'belgium', 'romania', 'italy',
       'poland', 'india', 'ireland',
       'socialist_federal_republic_of_yugoslavia', 'japan', 'hungary',
       'czech_republic', 'south_africa', 'mexico', 'australia', 'chile',
       'israel', 'austria', 'spain', 'lebanon',
       "people's_republic_of_china", 'south_korea', 'serbia',
       'soviet_union', 'georgia', 'croatia',
       'republic_of_china_(1912–1949)', 'turkey', 'brazil', 'portugal',
       'senegal', 'belarus', 'nicaragua', 'bulgaria', 'colombia',
       'thailand', 'slovenia', 'latvia', 'bosnia_and_herzegovina',
       'democratic_republic_of_the_congo', 'western_sahara', 'cyprus',
       'albania', 'lithuania', 'taiwan', 'uruguay',
       'republic_of_macedonia', 'iceland', 'peru', 'yugoslavia',
       'trinidad_and_tobago', 'ivory_coast', 'zambia', 'tunisia', 'malta',
       'somalia', 'libya', 'morocco', 'djibouti', 'angola', 'barbados',
       'england', 'panama', 'puerto_rico', 'northern_ireland', 'egypt',
       'andorra', 'ecuador', 'algeria', 'mali', 'ghana', 'cuba', 'kenya',
       'cameroon', 'haiti', 'nepal', 'saudi_arabia', 'azerbaijan',
       'afghanistan', 'ethiopia', 'niger', 'slovakia', 'iraq', 'scotland',
       'luxembourg', 'philippines', 'pakistan', 'mongolia', 'kuwait',
       'sudan', 'armenia', 'myanmar', 'republic_of_the_congo',
       'north_korea', 'honduras', 'syria', 'antigua_and_barbuda', 'benin',
       'czechoslovakia', 'china', 'sri_lanka', 'bolivia', 'moldova',
       'san_marino', 'cambodia', 'kazakhstan', 'zimbabwe', 'malaysia',
       'dominican_republic', 'paraguay', 'indonesia',
       'state_of_palestine', 'burkina_faso',
       'federated_states_of_micronesia', 'vietnam', 'burundi',
       'second_polish_republic', 'costa_rica', 'liechtenstein',
       'tanzania', 'singapore', 'bahamas', 'wales', 'british_raj', 'laos',
       'montenegro', 'jordan', 'german_democratic_republic', 'guinea',
       'namibia', 'bahrain', 'guatemala', 'monaco', 'québec-comté',
       'quebec', 'gambia', 'uzbekistan', 'united_arab_emirates',
       'faroe_islands', 'nauru', 'saint_kitts_and_nevis', 'dominica',
       'suriname', 'hong_kong', 'bangladesh',
       "people's_republic_of_poland", 'serbia_and_montenegro', 'qatar',
       'nazi_germany', 'palestine', 'uganda', 'chad', 'tonga', 'guyana',
       'el_salvador', 'turkmenistan', 'central_african_republic',
       'kiribati', 'kingdom_of_yugoslavia', 'kosovo', 'palau',
       'weimar_republic', 'madagascar', 'kingdom_of_denmark',
       'saint_vincent_and_the_grenadines', 'rwanda', 'papua_new_guinea',
       'cape_verde', 'liberia', 'israelis', 'togo',
       'palestinian_national_authority', 'kyrgyzstan', 'empire_of_japan',
       'sierra_leone', 'samoa', 'east_timor',
       'russian_soviet_federative_socialist_republic', 'mauritius',
       'greenland', 'mozambique', 'tuvalu',
       'kingdom_of_serbs,_croatians_and_slovenes', 'range_of_andia',
       'tibet', 'eswatini', 'mandatory_palestine', 'mauritania',
       'kingdom_of_italy', 'turkish_republic_of_northern_cyprus', 'yemen',
       'kingdom_of_romania', 'aruba', 'lesotho', 'marítimo', 'chilena',
       'oman', 'grenada', 'botswana', 'canadian_french', 'fiji', 'gabon',
       'equatorial_guinea', 'transnistria', 'great_britain', 'malawi',
       'eritrea', 'german', 'guam', 'kingdom_of_iraq', 'south_sudan',
       'korea', 'tajikistan', 'guinea-bissau', 'bhutan', 'dominican',
       'ukrainian_soviet_socialist_republic', 'egyptians', 'francia',
       'ukrainians', 'brunei', 'são_tomé_and_príncipe', 'artsakh',
       'belize', 'seychelles', 'maldives',
       'federal_republic_of_yugoslavia', 'dominicana', 'curaçao',
       'bermuda', 'armenian_soviet_socialist_republic',
       'kingdom_of_egypt', 'méxico', 'madrid', 'comoros',
       'francoist_spain', 'protectorate_of_bohemia_and_moravia',
       'west_germany', 'solomon_islands', 'saint_lucia',
       'colonial_nigeria', 'kingdom_of_hungary',
       "people's_republic_of_hungary", 'south_vietnam', 'vanuatu',
       'isle_of_man', 'kurdistan', 'manchukuo',
       'czechoslovak_socialist_republic', 'british_hong_kong',
       'slovak_state_(1939-1945)', 'kingdom_of_bulgaria',
       "people's_republic_of_bulgaria", 'sultanate_of_zanzibar',
       'dutch_east_indies', 'germans', 'guernsey', 'french_algeria',
       'marshall_islands', 'byelorussian_soviet_socialist_republic',
       'the_republic_of_abkhazia', 'japanese_people', 'welsh_people',
       'british_people', 'rhodesia', 'hungarian',
       'united_federation_of_planets',
       'federation_of_rhodesia_and_nyasaland',
       'socialist_republic_of_romania', 'kingdom_of_albania', 'katun',
       'iraqi_kurdistan', 'siciliana', 'soviètic',
       'first_hungarian_republic', 'union_of_south_africa',
       'indian_people', 'cook_islands',
       'georgian_soviet_socialist_republic', 'staffanstorp_municipality',
       'nuu-chah-nulth', 'southern_rhodesia', 'niue', 'croacia',
       'liberland', 'british_virgin_islands', 'american_samoa', 'danish',
       'spain_under_the_restoration', 'kingdom_of_afghanistan',
       'first_republic_of_austria', 'british_empire', 'kingdom_of_greece',
       'belgian_congo', 'murcia', 'macau',
       "people's_socialist_republic_of_albania", 'venezolano.',
       'yemen_arab_republic', 'estado_novo', 'vatican_city',
       'kenya_colony', 'tibet_from_1912_to_1951', 'montserrat',
       'ruanda-urundi', 'german_empire', 'ivanteyevskaya_street', 'perú',
       'kuwait_city', 'nepali',
       'united_kingdom_of_great_britain_and_ireland', 'tuva_republic',
       'statelessness', 'austrians', 'british_national_(overseas)',
       'filipino_people', 'lithuanian_soviet_socialist_republic',
       'country_of_the_kingdom_of_the_netherlands',
       'netherlands_antilles', 'gibraltar', 'florence', 'chechens',
       'republic_of_upper_volta', 'first_portuguese_republic',
       'monterrey', 'colombiana', "romanian_people's_republic",
       'ss_france', 'anguilla', "mongolian_people's_republic",
       'francais_objective_specifique', 'democratic_republic_of_georgia',
       'mexico_city', 'morocco_pavilion', 'française', 'french',
       'brazil–uruguay_relations', 'ecuador_national_football_team',
       'malays', 'azerbaijani', 'bangladeshis', 'bulgarian', 'italians',
       'american_occupation_zone', 'republic_of_cuba_(1902–59)',
       'langnau_am_albis', "federal_people's_republic_of_yugoslavia",
       'third_czechoslovak_republic', 'south_yemen', 'irish_republic',
       'british_somaliland', 'chinese_taipei', 'plastin', 'bosniaks',
       'oaxaca', 'brazi', 'tibetan_people', 'tabasco',
       'kingdom_of_mysore', 'beiyang_government', 'nazareth', 'afrika',
       'equestria', 'suisse_romande', 'republika_srpska',
       'san_luis_potosí', 'república_de_síria', 'americans', 'equatoria',
       'chileans', 'sint_maarten', 'hungarians', 'norwegian', 'afghan',
       'assam', 'irish', 'tamil_eelam', 'czechoslovak_republic',
       'sockel_fm2+', 'mexicana', 'canadian_nationality_law',
       'bicycle_kick', 'santo_domingo', 'québécois', 'cayman_islands',
       'são_paulo'], dtype=object)

In [21]:
df[df["nationality"] == "china"].head(10)

,id,label,nationality,date_of_birth,year_of_birth,image
1525,Q367219,Paul Shan Kuo-hsi,china,1923-12-03T00:00:00Z,1923,https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Paul_Shan_Kuo-hsi_(cropped).jpg/200px-Paul_Shan_Kuo-hsi_(cropped).jpg
4841,Q659792,Shi Jiuyong,china,1926-10-09T00:00:00Z,1926,https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Shi_Jiuyong_2005.jpg/200px-Shi_Jiuyong_2005.jpg
9388,Q1396639,Qin Yi,china,1922-01-31T00:00:00Z,1922,https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/秦怡.jpg/200px-秦怡.jpg
95578,Q731003,Sun Daolin,china,1921-12-18T00:00:00Z,1921,https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Screenshot_from_The_Eternal_Wave.jpg/200px-Screenshot_from_The_Eternal_Wave.jpg
96889,Q964071,Victor Wong,china,1927-07-30T00:00:00Z,1927,https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Victorwong2.jpg/200px-Victorwong2.jpg
138498,Q545613,Bai Yang,china,1920-04-22T00:00:00Z,1920,https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Bai_Yang.jpg/200px-Bai_Yang.jpg
139822,Q714897,Domingos Lam,china,1928-04-09T00:00:00Z,1928,https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/O_Domingos_Lam_tinha_30_anos.jpg/200px-O_Domingos_Lam_tinha_30_anos.jpg
141523,Q973070,Gaétan D'Amours,china,1933-01-01T00:00:00Z,1933,https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Gaétan_D'Amours.jpg/200px-Gaétan_D'Amours.jpg
177905,Q113652,Richard Frey,china,1920-02-11T00:00:00Z,1920,https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Richard_Frey-1.jpg/200px-Richard_Frey-1.jpg
201825,Q5094238,Cheung Chi Doy,china,1941-07-30T00:00:00Z,1941,https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Cheung_Chi_Doy.jpg/200px-Cheung_Chi_Doy.jpg

In [22]:
df[df["nationality"] == "japan"].head(10)

,id,label,nationality,date_of_birth,year_of_birth,image
55,Q264290,Mizuho Fukushima,japan,1955-12-24T00:00:00Z,1955,https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Mizuho_Fukushima_cropped_Mizuho_Fukushima_Shinjuku_20070610.jpg/200px-Mizuho_Fukushima_cropped_Mizuho_Fukushima_Shinjuku_20070610.jpg
72,Q265061,Moto Hagio,japan,1949-05-12T00:00:00Z,1949,https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Hagio_Moto_in_2008.jpg/200px-Hagio_Moto_in_2008.jpg
108,Q266873,Yuki Nagasato,japan,1987-07-15T00:00:00Z,1987,https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Yūki_Nagasato_2012.jpg/200px-Yūki_Nagasato_2012.jpg
316,Q275965,Yohei Kajiyama,japan,1985-09-24T00:00:00Z,1985,https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Yohei_Kajiyama.jpg/200px-Yohei_Kajiyama.jpg
413,Q285832,Kokia,japan,1976-07-22T00:00:00Z,1976,https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Kokiainconcert.jpg/200px-Kokiainconcert.jpg
432,Q288114,Joe Odagiri,japan,1976-02-16T00:00:00Z,1976,"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Odagiri_Joe_""Foujita""_at_Opening_Ceremony_of_the_28th_Tokyo_International_Film_Festival_(22265705578).jpg/200px-Odagiri_Joe_""Foujita""_at_Opening_Ceremony_of_the_28th_Tokyo_International_Film_Festival_(22265705578).jpg"
488,Q292113,Asuna Tanaka,japan,1988-04-23T00:00:00Z,1988,https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Asuna_Tanaka_2012_(cropped).jpg/200px-Asuna_Tanaka_2012_(cropped).jpg
492,Q292331,Ayumi Kaihori,japan,1986-09-04T00:00:00Z,1986,https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Ayumi_Kaihori_2015_(cropped).jpg/200px-Ayumi_Kaihori_2015_(cropped).jpg
620,Q303805,Verbal,japan,1975-08-21T00:00:00Z,1975,https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Teriyaki_Boyz_VERBAL_crop.jpg/200px-Teriyaki_Boyz_VERBAL_crop.jpg
632,Q306665,miwa,japan,1990-06-15T00:00:00Z,1990,"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Miwa_on_August_30,_2014.jpg/200px-Miwa_on_August_30,_2014.jpg"

In [23]:
base_dir = "Download_Images"

In [24]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Referer": "https://commons.wikimedia.org/"
}

In [25]:
import os
import requests
import cv2
import shutil

# Giả sử bạn đã có DataFrame df, headers và base_dir từ trước
# Lọc danh sách chỉ gồm những người có quốc tịch Nhật Bản
try:
    df_japan = df[df["nationality"] == "japan"]
except NameError:
    raise NameError("DataFrame 'df' chưa được định nghĩa. Vui lòng xác định 'df' chứa dữ liệu trước khi chạy script.")

# Thư mục lưu ảnh cho Japan (lưu vào japan2)
oj_dir = os.path.join(base_dir, "japan2")
os.makedirs(oj_dir, exist_ok=True)

# Load Haar Cascade
haar_xml_path = 'haarcascade_frontalface_default.xml'
face_cascade = cv2.CascadeClassifier(haar_xml_path)
if face_cascade.empty():
    raise FileNotFoundError(f"Không tìm thấy file Haar Cascade tại: {haar_xml_path}")

# Hàm crop vuông và resize về 160x160
def crop_and_resize_square(img, x, y, w, h, size=160):
    side = max(w, h)
    cx, cy = x + w // 2, y + h // 2
    x1 = max(cx - side // 2, 0)
    y1 = max(cy - side // 2, 0)
    x2 = min(x1 + side, img.shape[1])
    y2 = min(y1 + side, img.shape[0])
    x1 = max(x2 - side, 0)
    y1 = max(y2 - side, 0)
    square = img[y1:y2, x1:x2]
    resized = cv2.resize(square, (size, size), interpolation=cv2.INTER_AREA)
    return resized

# Nhóm các ảnh theo nhãn giống nhau trong df_japan
for idx, (label, group) in enumerate(df_japan.groupby("label"), start=1):
    save_dir = os.path.join(oj_dir, str(idx))
    os.makedirs(save_dir, exist_ok=True)
    valid_files = []

    for row in group.itertuples(index=False):
        image_url = row.image
        image_id = row.id
        try:
            response = requests.get(image_url, headers=headers, timeout=10)
            if response.status_code == 200:
                file_path = os.path.join(save_dir, f"{image_id}.jpg")
                with open(file_path, "wb") as file:
                    file.write(response.content)

                img = cv2.imread(file_path)
                if img is None:
                    print(f"Ảnh {file_path} bị hỏng, đã xóa.")
                    os.remove(file_path)
                    continue

                gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                faces = face_cascade.detectMultiScale(
                    gray,
                    scaleFactor=1.1,
                    minNeighbors=5,
                    minSize=(30, 30),
                    flags=cv2.CASCADE_SCALE_IMAGE
                )

                if len(faces) == 0:
                    os.remove(file_path)
                    print(f"Xóa ảnh {file_path}: không có khuôn mặt")
                else:
                    x, y, w, h = faces[0]
                    face_resized = crop_and_resize_square(img, x, y, w, h, size=160)
                    cv2.imwrite(file_path, face_resized)

                    valid_files.append(file_path)
                    print(f"Giữ ảnh {file_path}: phát hiện {len(faces)} khuôn mặt")
            else:
                print(f"Lỗi tải ảnh {image_id}: {response.status_code}")
        except Exception as e:
            print(f"Lỗi khi xử lý ảnh {image_id}: {e}")

    if not valid_files:
        try:
            shutil.rmtree(save_dir, ignore_errors=True)
            print(f"Đã xóa thư mục {save_dir} (không có ảnh hợp lệ)")
        except Exception as e:
            print(f"Lỗi khi xóa thư mục {save_dir}: {e}")
    else:
        print(f"Thư mục {save_dir} giữ lại do có {len(valid_files)} ảnh hợp lệ")

print("Hoàn thành!")

Xóa ảnh Download_Images\japan2\1\Q11189159.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\1 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\2\Q4666022.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\2 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\3\Q4689412.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\3 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\4\Q173197.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\4 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\5\Q239371.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\5 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\6\Q4244195.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\6 giữ lại do có 1 ảnh hợp lệ
Lỗi tải ảnh Q4216254: 404
Đã xóa thư mục Download_Images\japan2\7 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\8\Q7303351.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\8 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\9\Q11520666.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\9 giữ lại do có 1 ảnh hợp lệ
Lỗi tải ảnh Q11551890: 404
Đã xóa thư mục Download_Images\japan2\10 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\11\Q1155343.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\11 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\12\Q1041758.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\12 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\13\Q11357297.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\13 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\14\Q2827751.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\14 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\15\Q15524982.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\15 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\16\Q1323358.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\16 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\17\Q11425056.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\17 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\18\Q1191976.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\18 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\19\Q229100.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\19 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\20\Q230430.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\20 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\21\Q403264.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\21 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\22\Q403271.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\22 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\23\Q11358559.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\23 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\24\Q220079.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\24 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\25\Q7981253.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\25 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\26\Q8916509.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\26 (không có ảnh hợp lệ)
Lỗi tải ảnh Q11359300: 404
Đã xóa thư mục Download_Images\japan2\27 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\28\Q237348.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\28 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\29\Q11641621.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\29 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\30\Q242975.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\30 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\31\Q17215445.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\31 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\32\Q4696975.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\32 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\33\Q17160619.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\33 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\34\Q743509.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\34 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\35\Q4697155.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\35 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\36\Q11383270.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\36 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\37\Q11410301.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\37 (không có ảnh hợp lệ)
Lỗi tải ảnh Q576776: 404
Đã xóa thư mục Download_Images\japan2\38 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\39\Q11578634.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\39 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\40\Q16770405.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\40 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\41\Q1143678.jpg: phát hiện 1 khuôn mặt
Xóa ảnh Download_Images\japan2\41\Q4116788.jpg: không có khuôn mặt
Thư mục Download_Images\japan2\41 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\42\Q17160115.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\42 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\43\Q702652.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\43 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\44\Q1827239.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\44 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\45\Q27685650.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\45 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\46\Q19363236.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\46 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\47\Q16596833.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\47 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\48\Q18054823.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\48 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\49\Q11365974.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\49 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\50\Q17160530.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\50 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\51\Q415740.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\51 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\52\Q11469342.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\52 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\53\Q9152068.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\53 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\54\Q9070834.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\54 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\55\Q2909691.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\55 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\56\Q9187562.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\56 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\57\Q1191506.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\57 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\58\Q4700606.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\58 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\59\Q11473895.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\59 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\60\Q2255285.jpg: phát hiện 2 khuôn mặt
Thư mục Download_Images\japan2\60 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\61\Q11359398.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\61 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\62\Q2829021.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\62 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\63\Q417910.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\63 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\64\Q11470589.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\64 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\65\Q73358.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\65 giữ lại do có 1 ảnh hợp lệ
Lỗi tải ảnh Q11362714: 404
Đã xóa thư mục Download_Images\japan2\66 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\67\Q11656832.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\67 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\68\Q4700902.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\68 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\69\Q11496964.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\69 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\70\Q418046.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\70 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\71\Q375641.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\71 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\72\Q17129235.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\72 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\73\Q4700915.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\73 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\74\Q11367142.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\74 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\75\Q4700920.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\75 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\76\Q17350330.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\76 (không có ảnh hợp lệ)
Lỗi tải ảnh Q845978: 404
Đã xóa thư mục Download_Images\japan2\77 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\78\Q4700931.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\78 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\79\Q11531244.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\79 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\80\Q1076203.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\80 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\81\Q418119.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\81 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\82\Q16265047.jpg: phát hiện 2 khuôn mặt
Thư mục Download_Images\japan2\82 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\83\Q11668488.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\83 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\84\Q11534483.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\84 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\85\Q850850.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\85 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\86\Q337406.jpg: phát hiện 2 khuôn mặt
Thư mục Download_Images\japan2\86 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\87\Q418129.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\87 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\88\Q4700952.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\88 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\89\Q4700951.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\89 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\90\Q11373195.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\90 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\91\Q11529873.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\91 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\92\Q5924529.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\92 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\93\Q2829034.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\93 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\94\Q11665593.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\94 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\95\Q17129503.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\95 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\96\Q289559.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\96 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\97\Q4700991.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\97 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\98\Q11432106.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\98 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\99\Q1143664.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\99 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\100\Q11364942.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\100 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\101\Q4701066.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\101 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\102\Q4701067.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\102 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\103\Q1071877.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\103 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\104\Q360661.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\104 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\105\Q11575537.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\105 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\106\Q4701072.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\106 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\107\Q848767.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\107 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\108\Q4588104.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\108 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\109\Q11451529.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\109 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\110\Q3435725.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\110 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\111\Q18818091.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\111 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\112\Q1074807.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\112 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\113\Q1812050.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\113 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\114\Q310845.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\114 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\115\Q1652849.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\115 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\116\Q4701110.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\116 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\117\Q486599.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\117 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\118\Q8786903.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\118 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\119\Q11560942.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\119 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\120\Q418622.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\120 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\121\Q28689760.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\121 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\122\Q418675.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\122 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\123\Q418693.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\123 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\124\Q418691.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\124 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\125\Q418715.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\125 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\126\Q9316735.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\126 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\127\Q2829063.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\127 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\128\Q11551460.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\128 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\129\Q11596992.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\129 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\130\Q23905070.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\130 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\131\Q11475144.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\131 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\132\Q380690.jpg: phát hiện 2 khuôn mặt
Thư mục Download_Images\japan2\132 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\133\Q4701144.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\133 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\134\Q4701145.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\134 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\135\Q418771.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\135 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\136\Q2272969.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\136 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\137\Q3607342.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\137 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\138\Q4701157.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\138 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\139\Q4701154.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\139 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\140\Q337383.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\140 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\141\Q11531324.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\141 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\142\Q11356311.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\142 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\143\Q11388479.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\143 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\144\Q11523129.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\144 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\145\Q263777.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\145 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\146\Q4701163.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\146 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\147\Q3607345.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\147 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\148\Q210770.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\148 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\149\Q1928172.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\149 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\150\Q4701172.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\150 giữ lại do có 1 ảnh hợp lệ
Xóa ảnh Download_Images\japan2\151\Q8017067.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\151 (không có ảnh hợp lệ)
Xóa ảnh Download_Images\japan2\152\Q2829073.jpg: không có khuôn mặt
Đã xóa thư mục Download_Images\japan2\152 (không có ảnh hợp lệ)
Giữ ảnh Download_Images\japan2\153\Q418888.jpg: phát hiện 1 khuôn mặt
Thư mục Download_Images\japan2\153 giữ lại do có 1 ảnh hợp lệ
Giữ ảnh Download_Images\japan2\154\Q418911.jpg: phát hiện 1 khuôn mặt

In [26]:
# Bước 1: Lấy danh sách các thư mục hiện có trong 'oj_dir'
existing_folders = [f for f in os.listdir(oj_dir) if os.path.isdir(os.path.join(oj_dir, f))]

# Bước 2: Sắp xếp thư mục theo số thứ tự (nếu có)
existing_folders.sort(key=lambda x: int(x) if x.isdigit() else float('inf'))

# Bước 3: Đánh số lại từ 1 và đổi tên thư mục
for new_idx, old_folder_name in enumerate(existing_folders, start=1):
    old_path = os.path.join(oj_dir, old_folder_name)
    new_path = os.path.join(oj_dir, str(new_idx))
    
    # Nếu tên thư mục đã khác với số mới, đổi tên
    if old_folder_name != str(new_idx):
        try:
            os.rename(old_path, new_path)
            print(f"Đã đổi tên {old_folder_name} → {new_idx}")
        except Exception as e:
            print(f"Lỗi khi đổi tên {old_folder_name}: {e}")

print("Đã đánh số lại thư mục xong!")

Đã đổi tên 4 → 1
Đã đổi tên 5 → 2
Đã đổi tên 6 → 3
Đã đổi tên 9 → 4
Đã đổi tên 13 → 5
Đã đổi tên 14 → 6
Đã đổi tên 16 → 7
Đã đổi tên 17 → 8
Đã đổi tên 20 → 9
Đã đổi tên 22 → 10
Đã đổi tên 23 → 11
Đã đổi tên 24 → 12
Đã đổi tên 28 → 13
Đã đổi tên 31 → 14
Đã đổi tên 32 → 15
Đã đổi tên 33 → 16
Đã đổi tên 36 → 17
Đã đổi tên 39 → 18
Đã đổi tên 40 → 19
Đã đổi tên 41 → 20
Đã đổi tên 42 → 21
Đã đổi tên 43 → 22
Đã đổi tên 44 → 23
Đã đổi tên 46 → 24
Đã đổi tên 52 → 25
Đã đổi tên 53 → 26
Đã đổi tên 54 → 27
Đã đổi tên 57 → 28
Đã đổi tên 58 → 29
Đã đổi tên 60 → 30
Đã đổi tên 61 → 31
Đã đổi tên 65 → 32
Đã đổi tên 69 → 33
Đã đổi tên 71 → 34
Đã đổi tên 73 → 35
Đã đổi tên 74 → 36
Đã đổi tên 78 → 37
Đã đổi tên 80 → 38
Đã đổi tên 81 → 39
Đã đổi tên 82 → 40
Đã đổi tên 83 → 41
Đã đổi tên 86 → 42
Đã đổi tên 87 → 43
Đã đổi tên 88 → 44
Đã đổi tên 91 → 45
Đã đổi tên 94 → 46
Đã đổi tên 95 → 47
Đã đổi tên 97 → 48
Đã đổi tên 98 → 49
Đã đổi tên 104 → 50
Đã đổi tên 105 → 51
Đã đổi tên 106 → 52
Đã đổi tên 108 → 53
Đã đổi tên 109 → 54
Đã đổi tên 111 → 55
Đã đổi tên 117 → 56
Đã đổi tên 119 → 57
Đã đổi tên 122 → 58
Đã đổi tên 123 → 59
Đã đổi tên 124 → 60
Đã đổi tên 127 → 61
Đã đổi tên 128 → 62
Đã đổi tên 132 → 63
Đã đổi tên 135 → 64
Đã đổi tên 137 → 65
Đã đổi tên 138 → 66
Đã đổi tên 140 → 67
Đã đổi tên 142 → 68
Đã đổi tên 144 → 69
Đã đổi tên 145 → 70
Đã đổi tên 147 → 71
Đã đổi tên 149 → 72
Đã đổi tên 150 → 73
Đã đổi tên 153 → 74
Đã đổi tên 154 → 75
Đã đổi tên 155 → 76
Đã đổi tên 157 → 77
Đã đổi tên 159 → 78
Đã đổi tên 161 → 79
Đã đổi tên 165 → 80
Đã đổi tên 166 → 81
Đã đổi tên 167 → 82
Đã đổi tên 171 → 83
Đã đổi tên 173 → 84
Đã đổi tên 174 → 85
Đã đổi tên 176 → 86
Đã đổi tên 177 → 87
Đã đổi tên 178 → 88
Đã đổi tên 180 → 89
Đã đổi tên 181 → 90
Đã đổi tên 183 → 91
Đã đổi tên 185 → 92
Đã đổi tên 186 → 93
Đã đổi tên 187 → 94
Đã đổi tên 190 → 95
Đã đổi tên 191 → 96
Đã đổi tên 193 → 97
Đã đổi tên 199 → 98
Đã đổi tên 201 → 99
Đã đổi tên 202 → 100
Đã đổi tên 204 → 101
Đã đổi tên 205 → 102
Đã đổi tên 206 → 103
Đã đổi tên 207 → 104
Đã đổi tên 209 → 105
Đã đổi tên 211 → 106
Đã đổi tên 213 → 107
Đã đổi tên 214 → 108
Đã đổi tên 217 → 109
Đã đổi tên 219 → 110
Đã đổi tên 220 → 111
Đã đổi tên 221 → 112
Đã đổi tên 224 → 113
Đã đổi tên 227 → 114
Đã đổi tên 228 → 115
Đã đổi tên 234 → 116
Đã đổi tên 237 → 117
Đã đổi tên 239 → 118
Đã đổi tên 240 → 119
Đã đổi tên 243 → 120
Đã đổi tên 244 → 121
Đã đổi tên 247 → 122
Đã đổi tên 250 → 123
Đã đổi tên 251 → 124
Đã đổi tên 253 → 125
Đã đổi tên 254 → 126
Đã đổi tên 255 → 127
Đã đổi tên 256 → 128
Đã đổi tên 259 → 129
Đã đổi tên 265 → 130
Đã đổi tên 266 → 131
Đã đổi tên 269 → 132
Đã đổi tên 270 → 133
Đã đổi tên 273 → 134
Đã đổi tên 277 → 135
Đã đổi tên 278 → 136
Đã đổi tên 281 → 137
Đã đổi tên 285 → 138
Đã đổi tên 288 → 139
Đã đổi tên 289 → 140
Đã đổi tên 291 → 141
Đã đổi tên 295 → 142
Đã đổi tên 297 → 143
Đã đổi tên 300 → 144
Đã đổi tên 302 → 145
Đã đổi tên 304 → 146
Đã đổi tên 305 → 147
Đã đổi tên 306 → 148
Đã đổi tên 312 → 149
Đã đổi tên 316 → 150
Đã đổi tên 318 → 151
Đã đổi tên 320 → 152
Đã đổi tên 324 → 153
Đã đổi tên 327 → 154
Đã đổi tên 328 → 155
Đã đổi tên 329 → 156
Đã đổi tên 330 → 157
Đã đổi tên 332 → 158
Đã đổi tên 333 → 159
Đã đổi tên 335 → 160
Đã đổi tên 337 → 161
Đã đổi tên 338 → 162
Đã đổi tên 341 → 163
Đã đổi tên 343 → 164
Đã đổi tên 344 → 165
Đã đổi tên 346 → 166
Đã đổi tên 347 → 167
Đã đổi tên 348 → 168
Đã đổi tên 349 → 169
Đã đổi tên 350 → 170
Đã đổi tên 351 → 171
Đã đổi tên 355 → 172
Đã đổi tên 357 → 173
Đã đổi tên 360 → 174
Đã đổi tên 361 → 175
Đã đổi tên 363 → 176
Đã đổi tên 364 → 177
Đã đổi tên 366 → 178
Đã đổi tên 367 → 179
Đã đổi tên 368 → 180
Đã đổi tên 369 → 181
Đã đổi tên 371 → 182
Đã đổi tên 373 → 183
Đã đổi tên 375 → 184
Đã đổi tên 376 → 185
Đã đổi tên 377 → 186
Đã đổi tên 378 → 187
Đã đổi tên 381 → 188
Đã đổi tên 382 → 189
Đã đổi tên 389 → 190
Đã đổi tên 390 → 191
Đã đổi tên 391 → 192
Đã đổi tên 392 → 193
Đã đổi tên 393 → 194
Đã đổi tên 394 → 195
Đã đổi tên 395 → 196
Đã đổi tên 396 → 197
Đã đổi tên 397 → 198
Đã đổi tên 400 → 199
Đã đổi tên 405 → 200
Đã đổi tên 408 → 201
Đã đổi tên 409 → 202
Đã đổi tên 410 → 203
Đã đổi tên 413 → 204
Đã đổi tên 414 → 205
Đã đổi tên 415 → 206
Đã đổi tên 416 → 207
Đã đổi tên 417 → 208
Đã đổi tên 420 → 209
Đã đổi tên 423 → 210
Đã đổi tên 424 → 211
Đã đổi tên 425 → 212
Đã đổi tên 426 → 213
Đã đổi tên 427 → 214
Đã đổi tên 429 → 215
Đã đổi tên 430 → 216
Đã đổi tên 431 → 217
Đã đổi tên 432 → 218
Đã đổi tên 433 → 219
Đã đổi tên 434 → 220
Đã đổi tên 435 → 221
Đã đổi tên 436 → 222
Đã đổi tên 437 → 223
Đã đổi tên 438 → 224
Đã đổi tên 440 → 225
Đã đổi tên 442 → 226
Đã đổi tên 443 → 227
Đã đổi tên 444 → 228
Đã đổi tên 448 → 229
Đã đổi tên 454 → 230
Đã đổi tên 455 → 231
Đã đổi tên 456 → 232
Đã đổi tên 457 → 233
Đã đổi tên 459 → 234
Đã đổi tên 463 → 235
Đã đổi tên 468 → 236
Đã đổi tên 469 → 237
Đã đổi tên 470 → 238
Đã đổi tên 471 → 239
Đã đổi tên 472 → 240
Đã đổi tên 473 → 241
Đã đổi tên 474 → 242
Đã đổi tên 475 → 243
Đã đổi tên 477 → 244
Đã đổi tên 478 → 245
Đã đổi tên 489 → 246
Đã đổi tên 490 → 247
Đã đổi tên 491 → 248
Đã đổi tên 492 → 249
Đã đổi tên 495 → 250
Đã đổi tên 497 → 251
Đã đổi tên 500 → 252
Đã đổi tên 506 → 253
Đã đổi tên 507 → 254
Đã đổi tên 512 → 255
Đã đổi tên 515 → 256
Đã đổi tên 520 → 257
Đã đổi tên 521 → 258
Đã đổi tên 522 → 259
Đã đổi tên 524 → 260
Đã đổi tên 526 → 261
Đã đổi tên 527 → 262
Đã đổi tên 528 → 263
Đã đổi tên 531 → 264
Đã đổi tên 533 → 265
Đã đổi tên 534 → 266
Đã đổi tên 535 → 267
Đã đổi tên 536 → 268
Đã đổi tên 537 → 269
Đã đổi tên 538 → 270
Đã đổi tên 539 → 271
Đã đổi tên 548 → 272
Đã đổi tên 551 → 273
Đã đổi tên 554 → 274
Đã đổi tên 555 → 275
Đã đổi tên 557 → 276
Đã đổi tên 558 → 277
Đã đổi tên 560 → 278
Đã đổi tên 561 → 279
Đã đổi tên 563 → 280
Đã đổi tên 564 → 281
Đã đổi tên 565 → 282
Đã đổi tên 566 → 283
Đã đổi tên 570 → 284
Đã đổi tên 571 → 285
Đã đổi tên 574 → 286
Đã đổi tên 575 → 287
Đã đổi tên 579 → 288
Đã đổi tên 580 → 289
Đã đổi tên 581 → 290
Đã đổi tên 582 → 291
Đã đổi tên 588 → 292
Đã đổi tên 592 → 293
Đã đổi tên 593 → 294
Đã đổi tên 594 → 295
Đã đổi tên 595 → 296
Đã đổi tên 599 → 297
Đã đổi tên 601 → 298
Đã đổi tên 602 → 299
Đã đổi tên 608 → 300
Đã đổi tên 609 → 301
Đã đổi tên 613 → 302
Đã đổi tên 615 → 303
Đã đổi tên 619 → 304
Đã đổi tên 620 → 305
Đã đổi tên 621 → 306
Đã đổi tên 624 → 307
Đã đổi tên 625 → 308
Đã đổi tên 630 → 309
Đã đổi tên 631 → 310
Đã đổi tên 632 → 311
Đã đổi tên 633 → 312
Đã đổi tên 634 → 313
Đã đổi tên 636 → 314
Đã đổi tên 638 → 315
Đã đổi tên 639 → 316
Đã đổi tên 640 → 317
Đã đổi tên 641 → 318
Đã đổi tên 642 → 319
Đã đổi tên 643 → 320
Đã đổi tên 644 → 321
Đã đổi tên 645 → 322
Đã đổi tên 646 → 323
Đã đổi tên 647 → 324
Đã đổi tên 648 → 325
Đã đổi tên 650 → 326
Đã đổi tên 651 → 327
Đã đổi tên 653 → 328
Đã đổi tên 654 → 329
Đã đổi tên 655 → 330
Đã đổi tên 656 → 331
Đã đổi tên 657 → 332
Đã đổi tên 661 → 333
Đã đổi tên 666 → 334
Đã đổi tên 667 → 335
Đã đổi tên 668 → 336
Đã đổi tên 669 → 337
Đã đổi tên 670 → 338
Đã đổi tên 671 → 339
Đã đổi tên 673 → 340
Đã đổi tên 674 → 341
Đã đổi tên 675 → 342
Đã đổi tên 676 → 343
Đã đổi tên 679 → 344
Đã đổi tên 684 → 345
Đã đổi tên 685 → 346
Đã đổi tên 686 → 347
Đã đổi tên 690 → 348
Đã đổi tên 691 → 349
Đã đổi tên 692 → 350
Đã đổi tên 695 → 351
Đã đổi tên 697 → 352
Đã đổi tên 698 → 353
Đã đổi tên 699 → 354
Đã đổi tên 703 → 355
Đã đổi tên 705 → 356
Đã đổi tên 707 → 357
Đã đổi tên 708 → 358
Đã đổi tên 709 → 359
Đã đổi tên 712 → 360
Đã đổi tên 714 → 361
Đã đổi tên 715 → 362
Đã đổi tên 716 → 363
Đã đổi tên 721 → 364
Đã đổi tên 722 → 365
Đã đổi tên 724 → 366
Đã đổi tên 730 → 367
Đã đổi tên 731 → 368
Đã đổi tên 732 → 369
Đã đổi tên 734 → 370
Đã đổi tên 735 → 371
Đã đổi tên 738 → 372
Đã đổi tên 739 → 373
Đã đổi tên 740 → 374
Đã đổi tên 742 → 375
Đã đổi tên 745 → 376
Đã đổi tên 746 → 377
Đã đổi tên 747 → 378
Đã đổi tên 748 → 379
Đã đổi tên 749 → 380
Đã đổi tên 750 → 381
Đã đổi tên 751 → 382
Đã đổi tên 752 → 383
Đã đổi tên 753 → 384
Đã đổi tên 754 → 385
Đã đổi tên 755 → 386
Đã đổi tên 756 → 387
Đã đổi tên 757 → 388
Đã đổi tên 764 → 389
Đã đổi tên 766 → 390
Đã đổi tên 767 → 391
Đã đổi tên 768 → 392
Đã đổi tên 770 → 393
Đã đổi tên 771 → 394
Đã đổi tên 773 → 395
Đã đổi tên 774 → 396
Đã đổi tên 778 → 397
Đã đổi tên 780 → 398
Đã đổi tên 782 → 399
Đã đổi tên 783 → 400
Đã đổi tên 784 → 401
Đã đổi tên 785 → 402
Đã đổi tên 786 → 403
Đã đổi tên 787 → 404
Đã đổi tên 788 → 405
Đã đổi tên 790 → 406
Đã đổi tên 792 → 407
Đã đổi tên 795 → 408
Đã đổi tên 800 → 409
Đã đổi tên 801 → 410
Đã đổi tên 802 → 411
Đã đổi tên 806 → 412
Đã đổi tên 808 → 413
Đã đổi tên 811 → 414
Đã đổi tên 815 → 415
Đã đổi tên 818 → 416
Đã đổi tên 820 → 417
Đã đổi tên 823 → 418
Đã đổi tên 824 → 419
Đã đổi tên 827 → 420
Đã đổi tên 828 → 421
Đã đổi tên 831 → 422
Đã đổi tên 834 → 423
Đã đổi tên 839 → 424
Đã đổi tên 841 → 425
Đã đổi tên 845 → 426
Đã đổi tên 846 → 427
Đã đổi tên 847 → 428
Đã đổi tên 849 → 429
Đã đổi tên 850 → 430
Đã đổi tên 852 → 431
Đã đổi tên 855 → 432
Đã đổi tên 858 → 433
Đã đổi tên 860 → 434
Đã đổi tên 865 → 435
Đã đổi tên 866 → 436
Đã đổi tên 867 → 437
Đã đổi tên 868 → 438
Đã đổi tên 869 → 439
Đã đổi tên 870 → 440
Đã đổi tên 872 → 441
Đã đổi tên 874 → 442
Đã đổi tên 879 → 443
Đã đổi tên 886 → 444
Đã đổi tên 887 → 445
Đã đổi tên 888 → 446
Đã đổi tên 889 → 447
Đã đổi tên 890 → 448
Đã đổi tên 892 → 449
Đã đổi tên 893 → 450
Đã đổi tên 894 → 451
Đã đổi tên 897 → 452
Đã đổi tên 899 → 453
Đã đổi tên 902 → 454
Đã đổi tên 903 → 455
Đã đổi tên 904 → 456
Đã đổi tên 905 → 457
Đã đổi tên 907 → 458
Đã đổi tên 909 → 459
Đã đổi tên 910 → 460
Đã đổi tên 912 → 461
Đã đổi tên 913 → 462
Đã đổi tên 914 → 463
Đã đổi tên 916 → 464
Đã đổi tên 917 → 465
Đã đổi tên 920 → 466
Đã đổi tên 922 → 467
Đã đổi tên 923 → 468
Đã đổi tên 924 → 469
Đã đổi tên 928 → 470
Đã đổi tên 932 → 471
Đã đổi tên 933 → 472
Đã đổi tên 934 → 473
Đã đổi tên 935 → 474
Đã đổi tên 938 → 475
Đã đổi tên 946 → 476
Đã đổi tên 949 → 477
Đã đổi tên 950 → 478
Đã đổi tên 951 → 479
Đã đổi tên 953 → 480
Đã đổi tên 955 → 481
Đã đổi tên 956 → 482
Đã đổi tên 959 → 483
Đã đổi tên 962 → 484
Đã đổi tên 963 → 485
Đã đổi tên 964 → 486
Đã đổi tên 965 → 487
Đã đổi tên 968 → 488
Đã đổi tên 971 → 489
Đã đổi tên 973 → 490
Đã đổi tên 974 → 491
Đã đổi tên 975 → 492
Đã đổi tên 977 → 493
Đã đổi tên 978 → 494
Đã đổi tên 982 → 495
Đã đổi tên 983 → 496
Đã đổi tên 984 → 497
Đã đổi tên 989 → 498
Đã đổi tên 990 → 499
Đã đổi tên 992 → 500
Đã đổi tên 995 → 501
Đã đổi tên 997 → 502
Đã đổi tên 998 → 503
Đã đổi tên 999 → 504
Đã đổi tên 1002 → 505
Đã đổi tên 1003 → 506
Đã đổi tên 1005 → 507
Đã đổi tên 1006 → 508
Đã đổi tên 1011 → 509
Đã đổi tên 1012 → 510
Đã đổi tên 1016 → 511
Đã đổi tên 1020 → 512
Đã đổi tên 1021 → 513
Đã đổi tên 1022 → 514
Đã đổi tên 1024 → 515
Đã đổi tên 1029 → 516
Đã đổi tên 1031 → 517
Đã đổi tên 1033 → 518
Đã đổi tên 1034 → 519
Đã đổi tên 1035 → 520
Đã đổi tên 1036 → 521
Đã đổi tên 1037 → 522
Đã đổi tên 1038 → 523
Đã đổi tên 1039 → 524
Đã đổi tên 1040 → 525
Đã đổi tên 1042 → 526
Đã đổi tên 1044 → 527
Đã đổi tên 1045 → 528
Đã đổi tên 1046 → 529
Đã đổi tên 1050 → 530
Đã đổi tên 1051 → 531
Đã đổi tên 1054 → 532
Đã đổi tên 1055 → 533
Đã đổi tên 1058 → 534
Đã đổi tên 1059 → 535
Đã đổi tên 1060 → 536
Đã đổi tên 1062 → 537
Đã đổi tên 1064 → 538
Đã đổi tên 1066 → 539
Đã đổi tên 1075 → 540
Đã đổi tên 1076 → 541
Đã đổi tên 1077 → 542
Đã đổi tên 1079 → 543
Đã đổi tên 1081 → 544
Đã đổi tên 1083 → 545
Đã đổi tên 1086 → 546
Đã đổi tên 1087 → 547
Đã đổi tên 1088 → 548
Đã đổi tên 1089 → 549
Đã đổi tên 1090 → 550
Đã đổi tên 1091 → 551
Đã đổi tên 1095 → 552
Đã đổi tên 1096 → 553
Đã đổi tên 1098 → 554
Đã đổi tên 1099 → 555
Đã đổi tên 1100 → 556
Đã đổi tên 1102 → 557
Đã đổi tên 1105 → 558
Đã đổi tên 1106 → 559
Đã đổi tên 1107 → 560
Đã đổi tên 1108 → 561
Đã đổi tên 1110 → 562
Đã đổi tên 1112 → 563
Đã đổi tên 1113 → 564
Đã đổi tên 1115 → 565
Đã đổi tên 1116 → 566
Đã đổi tên 1118 → 567
Đã đổi tên 1119 → 568
Đã đổi tên 1120 → 569
Đã đổi tên 1121 → 570
Đã đổi tên 1122 → 571
Đã đổi tên 1123 → 572
Đã đổi tên 1125 → 573
Đã đổi tên 1127 → 574
Đã đổi tên 1128 → 575
Đã đổi tên 1129 → 576
Đã đổi tên 1131 → 577
Đã đổi tên 1132 → 578
Đã đổi tên 1133 → 579
Đã đổi tên 1136 → 580
Đã đổi tên 1137 → 581
Đã đổi tên 1139 → 582
Đã đổi tên 1140 → 583
Đã đổi tên 1141 → 584
Đã đổi tên 1142 → 585
Đã đổi tên 1143 → 586
Đã đổi tên 1149 → 587
Đã đổi tên 1150 → 588
Đã đổi tên 1151 → 589
Đã đổi tên 1153 → 590
Đã đổi tên 1155 → 591
Đã đổi tên 1158 → 592
Đã đổi tên 1159 → 593
Đã đổi tên 1161 → 594
Đã đổi tên 1162 → 595
Đã đổi tên 1164 → 596
Đã đổi tên 1165 → 597
Đã đổi tên 1167 → 598
Đã đổi tên 1168 → 599
Đã đổi tên 1169 → 600
Đã đổi tên 1170 → 601
Đã đổi tên 1171 → 602
Đã đổi tên 1172 → 603
Đã đổi tên 1175 → 604
Đã đổi tên 1177 → 605
Đã đổi tên 1180 → 606
Đã đổi tên 1181 → 607
Đã đổi tên 1182 → 608
Đã đổi tên 1184 → 609
Đã đổi tên 1186 → 610
Đã đổi tên 1188 → 611
Đã đổi tên 1189 → 612
Đã đổi tên 1190 → 613
Đã đổi tên 1192 → 614
Đã đổi tên 1193 → 615
Đã đổi tên 1194 → 616
Đã đổi tên 1204 → 617
Đã đổi tên 1205 → 618
Đã đổi tên 1209 → 619
Đã đổi tên 1217 → 620
Đã đổi tên 1218 → 621
Đã đổi tên 1222 → 622
Đã đổi tên 1223 → 623
Đã đổi tên 1224 → 624
Đã đổi tên 1227 → 625
Đã đổi tên 1231 → 626
Đã đổi tên 1235 → 627
Đã đổi tên 1237 → 628
Đã đổi tên 1238 → 629
Đã đổi tên 1240 → 630
Đã đổi tên 1241 → 631
Đã đổi tên 1243 → 632
Đã đổi tên 1244 → 633
Đã đổi tên 1245 → 634
Đã đổi tên 1246 → 635
Đã đổi tên 1247 → 636
Đã đổi tên 1248 → 637
Đã đổi tên 1249 → 638
Đã đổi tên 1250 → 639
Đã đổi tên 1253 → 640
Đã đổi tên 1255 → 641
Đã đổi tên 1256 → 642
Đã đổi tên 1257 → 643
Đã đổi tên 1263 → 644
Đã đổi tên 1265 → 645
Đã đổi tên 1266 → 646
Đã đổi tên 1267 → 647
Đã đổi tên 1268 → 648
Đã đổi tên 1271 → 649
Đã đổi tên 1272 → 650
Đã đổi tên 1273 → 651
Đã đổi tên 1274 → 652
Đã đổi tên 1275 → 653
Đã đổi tên 1276 → 654
Đã đổi tên 1279 → 655
Đã đổi tên 1280 → 656
Đã đổi tên 1281 → 657
Đã đổi tên 1282 → 658
Đã đổi tên 1283 → 659
Đã đổi tên 1287 → 660
Đã đổi tên 1288 → 661
Đã đổi tên 1289 → 662
Đã đổi tên 1291 → 663
Đã đổi tên 1292 → 664
Đã đổi tên 1295 → 665
Đã đổi tên 1296 → 666
Đã đổi tên 1297 → 667
Đã đổi tên 1298 → 668
Đã đổi tên 1301 → 669
Đã đổi tên 1302 → 670
Đã đổi tên 1303 → 671
Đã đổi tên 1304 → 672
Đã đổi tên 1306 → 673
Đã đổi tên 1308 → 674
Đã đổi tên 1309 → 675
Đã đổi tên 1310 → 676
Đã đổi tên 1311 → 677
Đã đổi tên 1312 → 678
Đã đổi tên 1313 → 679
Đã đổi tên 1314 → 680
Đã đổi tên 1318 → 681
Đã đổi tên 1319 → 682
Đã đổi tên 1320 → 683
Đã đổi tên 1321 → 684
Đã đổi tên 1322 → 685
Đã đổi tên 1323 → 686
Đã đổi tên 1325 → 687
Đã đổi tên 1326 → 688
Đã đổi tên 1329 → 689
Đã đổi tên 1331 → 690
Đã đổi tên 1332 → 691
Đã đổi tên 1333 → 692
Đã đổi tên 1334 → 693
Đã đổi tên 1336 → 694
Đã đổi tên 1340 → 695
Đã đổi tên 1341 → 696
Đã đổi tên 1343 → 697
Đã đổi tên 1344 → 698
Đã đổi tên 1345 → 699
Đã đổi tên 1346 → 700
Đã đổi tên 1348 → 701
Đã đổi tên 1349 → 702
Đã đổi tên 1351 → 703
Đã đổi tên 1353 → 704
Đã đổi tên 1354 → 705
Đã đổi tên 1355 → 706
Đã đổi tên 1356 → 707
Đã đổi tên 1358 → 708
Đã đổi tên 1361 → 709
Đã đổi tên 1362 → 710
Đã đổi tên 1363 → 711
Đã đổi tên 1364 → 712
Đã đổi tên 1365 → 713
Đã đổi tên 1366 → 714
Đã đổi tên 1367 → 715
Đã đổi tên 1369 → 716
Đã đổi tên 1370 → 717
Đã đổi tên 1371 → 718
Đã đổi tên 1372 → 719
Đã đổi tên 1373 → 720
Đã đổi tên 1375 → 721
Đã đổi tên 1376 → 722
Đã đổi tên 1378 → 723
Đã đổi tên 1379 → 724
Đã đổi tên 1382 → 725
Đã đổi tên 1383 → 726
Đã đổi tên 1384 → 727
Đã đổi tên 1387 → 728
Đã đổi tên 1388 → 729
Đã đổi tên 1393 → 730
Đã đổi tên 1396 → 731
Đã đổi tên 1397 → 732
Đã đổi tên 1401 → 733
Đã đổi tên 1402 → 734
Đã đổi tên 1403 → 735
Đã đổi tên 1404 → 736
Đã đổi tên 1405 → 737
Đã đổi tên 1406 → 738
Đã đổi tên 1407 → 739
Đã đổi tên 1411 → 740
Đã đổi tên 1413 → 741
Đã đổi tên 1416 → 742
Đã đổi tên 1417 → 743
Đã đổi tên 1418 → 744
Đã đổi tên 1419 → 745
Đã đổi tên 1423 → 746
Đã đổi tên 1424 → 747
Đã đổi tên 1425 → 748
Đã đổi tên 1428 → 749
Đã đổi tên 1429 → 750
Đã đổi tên 1432 → 751
Đã đổi tên 1436 → 752
Đã đổi tên 1437 → 753
Đã đổi tên 1438 → 754
Đã đổi tên 1439 → 755
Đã đổi tên 1440 → 756
Đã đổi tên 1442 → 757
Đã đổi tên 1443 → 758
Đã đổi tên 1444 → 759
Đã đổi tên 1448 → 760
Đã đổi tên 1450 → 761
Đã đổi tên 1451 → 762
Đã đổi tên 1453 → 763
Đã đổi tên 1454 → 764
Đã đổi tên 1455 → 765
Đã đổi tên 1456 → 766
Đã đổi tên 1457 → 767
Đã đổi tên 1458 → 768
Đã đổi tên 1459 → 769
Đã đổi tên 1461 → 770
Đã đổi tên 1462 → 771
Đã đổi tên 1464 → 772
Đã đổi tên 1465 → 773
Đã đổi tên 1466 → 774
Đã đổi tên 1467 → 775
Đã đổi tên 1468 → 776
Đã đổi tên 1474 → 777
Đã đổi tên 1475 → 778
Đã đổi tên 1476 → 779
Đã đổi tên 1479 → 780
Đã đổi tên 1481 → 781
Đã đổi tên 1482 → 782
Đã đổi tên 1483 → 783
Đã đổi tên 1485 → 784
Đã đổi tên 1486 → 785
Đã đổi tên 1488 → 786
Đã đổi tên 1490 → 787
Đã đổi tên 1492 → 788
Đã đổi tên 1493 → 789
Đã đổi tên 1496 → 790
Đã đổi tên 1497 → 791
Đã đổi tên 1499 → 792
Đã đổi tên 1505 → 793
Đã đổi tên 1507 → 794
Đã đổi tên 1508 → 795
Đã đổi tên 1510 → 796
Đã đổi tên 1513 → 797
Đã đổi tên 1517 → 798
Đã đổi tên 1518 → 799
Đã đổi tên 1521 → 800
Đã đổi tên 1523 → 801
Đã đổi tên 1525 → 802
Đã đổi tên 1526 → 803
Đã đổi tên 1528 → 804
Đã đổi tên 1531 → 805
Đã đổi tên 1532 → 806
Đã đổi tên 1534 → 807
Đã đổi tên 1538 → 808
Đã đổi tên 1539 → 809
Đã đổi tên 1540 → 810
Đã đổi tên 1541 → 811
Đã đổi tên 1542 → 812
Đã đổi tên 1544 → 813
Đã đổi tên 1547 → 814
Đã đổi tên 1548 → 815
Đã đổi tên 1549 → 816
Đã đổi tên 1550 → 817
Đã đổi tên 1551 → 818
Đã đổi tên 1554 → 819
Đã đổi tên 1555 → 820
Đã đổi tên 1556 → 821
Đã đổi tên 1557 → 822
Đã đổi tên 1559 → 823
Đã đổi tên 1564 → 824
Đã đổi tên 1566 → 825
Đã đổi tên 1567 → 826
Đã đổi tên 1570 → 827
Đã đổi tên 1571 → 828
Đã đổi tên 1577 → 829
Đã đổi tên 1578 → 830
Đã đổi tên 1580 → 831
Đã đổi tên 1581 → 832
Đã đổi tên 1582 → 833
Đã đổi tên 1584 → 834
Đã đổi tên 1586 → 835
Đã đổi tên 1587 → 836
Đã đổi tên 1589 → 837
Đã đổi tên 1590 → 838
Đã đổi tên 1593 → 839
Đã đổi tên 1597 → 840
Đã đổi tên 1600 → 841
Đã đổi tên 1602 → 842
Đã đổi tên 1603 → 843
Đã đổi tên 1604 → 844
Đã đổi tên 1606 → 845
Đã đổi tên 1607 → 846
Đã đổi tên 1608 → 847
Đã đổi tên 1609 → 848
Đã đổi tên 1610 → 849
Đã đổi tên 1611 → 850
Đã đổi tên 1613 → 851
Đã đổi tên 1614 → 852
Đã đổi tên 1615 → 853
Đã đổi tên 1616 → 854
Đã đổi tên 1620 → 855
Đã đổi tên 1621 → 856
Đã đổi tên 1623 → 857
Đã đổi tên 1626 → 858
Đã đổi tên 1627 → 859
Đã đổi tên 1629 → 860
Đã đổi tên 1630 → 861
Đã đổi tên 1631 → 862
Đã đổi tên 1632 → 863
Đã đổi tên 1635 → 864
Đã đổi tên 1636 → 865
Đã đổi tên 1637 → 866
Đã đổi tên 1640 → 867
Đã đổi tên 1641 → 868
Đã đổi tên 1642 → 869
Đã đổi tên 1643 → 870
Đã đổi tên 1645 → 871
Đã đổi tên 1647 → 872
Đã đổi tên 1648 → 873
Đã đổi tên 1649 → 874
Đã đổi tên 1650 → 875
Đã đổi tên 1654 → 876
Đã đổi tên 1655 → 877
Đã đổi tên 1656 → 878
Đã đổi tên 1657 → 879
Đã đổi tên 1660 → 880
Đã đổi tên 1664 → 881
Đã đổi tên 1672 → 882
Đã đổi tên 1675 → 883
Đã đổi tên 1678 → 884
Đã đổi tên 1680 → 885
Đã đổi tên 1682 → 886
Đã đổi tên 1683 → 887
Đã đổi tên 1684 → 888
Đã đổi tên 1686 → 889
Đã đổi tên 1687 → 890
Đã đổi tên 1695 → 891
Đã đổi tên 1696 → 892
Đã đổi tên 1700 → 893
Đã đổi tên 1707 → 894
Đã đổi tên 1708 → 895
Đã đổi tên 1709 → 896
Đã đổi tên 1712 → 897
Đã đổi tên 1713 → 898
Đã đổi tên 1714 → 899
Đã đổi tên 1718 → 900
Đã đổi tên 1720 → 901
Đã đổi tên 1722 → 902
Đã đổi tên 1723 → 903
Đã đổi tên 1725 → 904
Đã đổi tên 1726 → 905
Đã đổi tên 1728 → 906
Đã đổi tên 1731 → 907
Đã đổi tên 1732 → 908
Đã đổi tên 1733 → 909
Đã đổi tên 1735 → 910
Đã đổi tên 1736 → 911
Đã đổi tên 1737 → 912
Đã đổi tên 1738 → 913
Đã đổi tên 1739 → 914
Đã đổi tên 1742 → 915
Đã đổi tên 1743 → 916
Đã đổi tên 1744 → 917
Đã đổi tên 1746 → 918
Đã đổi tên 1750 → 919
Đã đổi tên 1754 → 920
Đã đổi tên 1756 → 921
Đã đổi tên 1762 → 922
Đã đổi tên 1764 → 923
Đã đổi tên 1767 → 924
Đã đổi tên 1768 → 925
Đã đổi tên 1769 → 926
Đã đổi tên 1772 → 927
Đã đổi tên 1773 → 928
Đã đổi tên 1774 → 929
Đã đổi tên 1775 → 930
Đã đổi tên 1776 → 931
Đã đổi tên 1778 → 932
Đã đổi tên 1779 → 933
Đã đổi tên 1784 → 934
Đã đổi tên 1790 → 935
Đã đổi tên 1793 → 936
Đã đổi tên 1795 → 937
Đã đổi tên 1796 → 938
Đã đổi tên 1797 → 939

In [27]:
import os
import cv2
import numpy as np

# Đường dẫn gốc chứa các thư mục label (hãy đảm bảo biến base_dir được định nghĩa trước đó)
root_dir = os.path.join(base_dir, "japan2")

def augment_image(img):
    """
    Trả về list các tuple (suffix, augmented_image)
    Mỗi ảnh gốc sẽ sinh 5 biến thể:
      - 1 flip ngang
      - 2 xoay ±15°
      - 1 điều chỉnh độ sáng
      - 1 thêm nhiễu Gaussian
    Tổng 5 ảnh.
    """
    h, w = img.shape[:2]
    aug_list = []

    # 1. Flip ngang
    aug_list.append(('_flip', cv2.flip(img, 1)))

    # 2. Xoay ±15°
    for angle in (-15, 15):
        M = cv2.getRotationMatrix2D((w // 2, h // 2), angle, 1.0)
        rot = cv2.warpAffine(img, M, (w, h), borderMode=cv2.BORDER_REFLECT)
        aug_list.append((f'_rot{angle}', rot))

    # 3. Thay đổi độ sáng (alpha > 1 để làm sáng nhẹ)
    bright = cv2.convertScaleAbs(img, alpha=1.2, beta=0)
    aug_list.append(('_bright', bright))

    # 4. Thêm nhiễu Gaussian
    gauss = np.random.normal(0, 15, img.shape).astype(np.float32)
    noisy = cv2.add(img.astype(np.float32), gauss)
    noisy = np.clip(noisy, 0, 255).astype(np.uint8)
    aug_list.append(('_noise', noisy))

    return aug_list


if __name__ == '__main__':
    for label_folder in os.listdir(root_dir):
        folder_path = os.path.join(root_dir, label_folder)
        if not os.path.isdir(folder_path):
            continue

        for fname in os.listdir(folder_path):
            if not fname.lower().endswith('.jpg'):
                continue

            img_path = os.path.join(folder_path, fname)
            img = cv2.imread(img_path)
            if img is None:
                print(f"Không đọc được ảnh {img_path}, bỏ qua.")
                continue

            for suffix, aug_img in augment_image(img):
                name, ext = os.path.splitext(fname)
                out_name = f"{name}{suffix}{ext}"
                out_path = os.path.join(folder_path, out_name)
                cv2.imwrite(out_path, aug_img)
                print(f"Tạo: {out_path}")

    print("Tăng cường dữ liệu hoàn tất!")

Tạo: Download_Images\japan2\1\Q173197_flip.jpg
Tạo: Download_Images\japan2\1\Q173197_rot-15.jpg
Tạo: Download_Images\japan2\1\Q173197_rot15.jpg
Tạo: Download_Images\japan2\1\Q173197_bright.jpg
Tạo: Download_Images\japan2\1\Q173197_noise.jpg
Tạo: Download_Images\japan2\10\Q403271_flip.jpg
Tạo: Download_Images\japan2\10\Q403271_rot-15.jpg
Tạo: Download_Images\japan2\10\Q403271_rot15.jpg
Tạo: Download_Images\japan2\10\Q403271_bright.jpg
Tạo: Download_Images\japan2\10\Q403271_noise.jpg
Tạo: Download_Images\japan2\100\Q434189_flip.jpg
Tạo: Download_Images\japan2\100\Q434189_rot-15.jpg
Tạo: Download_Images\japan2\100\Q434189_rot15.jpg
Tạo: Download_Images\japan2\100\Q434189_bright.jpg
Tạo: Download_Images\japan2\100\Q434189_noise.jpg
Tạo: Download_Images\japan2\1000\Q9347752_flip.jpg
Tạo: Download_Images\japan2\1000\Q9347752_rot-15.jpg
Tạo: Download_Images\japan2\1000\Q9347752_rot15.jpg
Tạo: Download_Images\japan2\1000\Q9347752_bright.jpg
Tạo: Download_Images\japan2\1000\Q9347752_noise.jpg
Tạo: Download_Images\japan2\1001\Q6389316_flip.jpg
Tạo: Download_Images\japan2\1001\Q6389316_rot-15.jpg
Tạo: Download_Images\japan2\1001\Q6389316_rot15.jpg
Tạo: Download_Images\japan2\1001\Q6389316_bright.jpg
Tạo: Download_Images\japan2\1001\Q6389316_noise.jpg
Tạo: Download_Images\japan2\1002\Q16263616_flip.jpg
Tạo: Download_Images\japan2\1002\Q16263616_rot-15.jpg
Tạo: Download_Images\japan2\1002\Q16263616_rot15.jpg
Tạo: Download_Images\japan2\1002\Q16263616_bright.jpg
Tạo: Download_Images\japan2\1002\Q16263616_noise.jpg
Tạo: Download_Images\japan2\1003\Q6389323_flip.jpg
Tạo: Download_Images\japan2\1003\Q6389323_rot-15.jpg
Tạo: Download_Images\japan2\1003\Q6389323_rot15.jpg
Tạo: Download_Images\japan2\1003\Q6389323_bright.jpg
Tạo: Download_Images\japan2\1003\Q6389323_noise.jpg
Tạo: Download_Images\japan2\1004\Q3791180_flip.jpg
Tạo: Download_Images\japan2\1004\Q3791180_rot-15.jpg
Tạo: Download_Images\japan2\1004\Q3791180_rot15.jpg
Tạo: Download_Images\japan2\1004\Q3791180_bright.jpg
Tạo: Download_Images\japan2\1004\Q3791180_noise.jpg
Tạo: Download_Images\japan2\1005\Q195440_flip.jpg
Tạo: Download_Images\japan2\1005\Q195440_rot-15.jpg
Tạo: Download_Images\japan2\1005\Q195440_rot15.jpg
Tạo: Download_Images\japan2\1005\Q195440_bright.jpg
Tạo: Download_Images\japan2\1005\Q195440_noise.jpg
Tạo: Download_Images\japan2\1006\Q11410830_flip.jpg
Tạo: Download_Images\japan2\1006\Q11410830_rot-15.jpg
Tạo: Download_Images\japan2\1006\Q11410830_rot15.jpg
Tạo: Download_Images\japan2\1006\Q11410830_bright.jpg
Tạo: Download_Images\japan2\1006\Q11410830_noise.jpg
Tạo: Download_Images\japan2\1007\Q718906_flip.jpg
Tạo: Download_Images\japan2\1007\Q718906_rot-15.jpg
Tạo: Download_Images\japan2\1007\Q718906_rot15.jpg
Tạo: Download_Images\japan2\1007\Q718906_bright.jpg
Tạo: Download_Images\japan2\1007\Q718906_noise.jpg
Tạo: Download_Images\japan2\1008\Q2518786_flip.jpg
Tạo: Download_Images\japan2\1008\Q2518786_rot-15.jpg
Tạo: Download_Images\japan2\1008\Q2518786_rot15.jpg
Tạo: Download_Images\japan2\1008\Q2518786_bright.jpg
Tạo: Download_Images\japan2\1008\Q2518786_noise.jpg
Tạo: Download_Images\japan2\1009\Q443712_flip.jpg
Tạo: Download_Images\japan2\1009\Q443712_rot-15.jpg
Tạo: Download_Images\japan2\1009\Q443712_rot15.jpg
Tạo: Download_Images\japan2\1009\Q443712_bright.jpg
Tạo: Download_Images\japan2\1009\Q443712_noise.jpg
Tạo: Download_Images\japan2\101\Q236954_flip.jpg
Tạo: Download_Images\japan2\101\Q236954_rot-15.jpg
Tạo: Download_Images\japan2\101\Q236954_rot15.jpg
Tạo: Download_Images\japan2\101\Q236954_bright.jpg
Tạo: Download_Images\japan2\101\Q236954_noise.jpg
Tạo: Download_Images\japan2\1010\Q1383072_flip.jpg
Tạo: Download_Images\japan2\1010\Q1383072_rot-15.jpg
Tạo: Download_Images\japan2\1010\Q1383072_rot15.jpg
Tạo: Download_Images\japan2\1010\Q1383072_bright.jpg
Tạo: Download_Images\japan2\1010\Q1383072_noise.jpg
Tạo: Download_Images\japan2\1011\Q2293429_flip.jpg
Tạo: Download_Images\japan2\1011\Q2293429_rot-15.jpg
Tạo: Download_Images\japan2\1011\Q2293429_rot15.jpg
Tạo: Download_Images\japan2\1011\Q2293429_bright.jpg
Tạo: Download_Images\japan2\1011\Q2293429_noise.jpg
Tạo: Download_Images\japan2\1012\Q4298589_flip.jpg
Tạo: Download_Images\japan2\1012\Q4298589_rot-15.jpg
Tạo: Download_Images\japan2\1012\Q4298589_rot15.jpg
Tạo: Download_Images\japan2\1012\Q4298589_bright.jpg
Tạo: Download_Images\japan2\1012\Q4298589_noise.jpg
Tạo: Download_Images\japan2\1013\Q1155778_flip.jpg
Tạo: Download_Images\japan2\1013\Q1155778_rot-15.jpg
Tạo: Download_Images\japan2\1013\Q1155778_rot15.jpg
Tạo: Download_Images\japan2\1013\Q1155778_bright.jpg
Tạo: Download_Images\japan2\1013\Q1155778_noise.jpg
Tạo: Download_Images\japan2\1014\Q378715_flip.jpg
Tạo: Download_Images\japan2\1014\Q378715_rot-15.jpg
Tạo: Download_Images\japan2\1014\Q378715_rot15.jpg
Tạo: Download_Images\japan2\1014\Q378715_bright.jpg
Tạo: Download_Images\japan2\1014\Q378715_noise.jpg
Tạo: Download_Images\japan2\1015\Q11384480_flip.jpg
Tạo: Download_Images\japan2\1015\Q11384480_rot-15.jpg
Tạo: Download_Images\japan2\1015\Q11384480_rot15.jpg
Tạo: Download_Images\japan2\1015\Q11384480_bright.jpg
Tạo: Download_Images\japan2\1015\Q11384480_noise.jpg
Tạo: Download_Images\japan2\1016\Q11649298_flip.jpg
Tạo: Download_Images\japan2\1016\Q11649298_rot-15.jpg
Tạo: Download_Images\japan2\1016\Q11649298_rot15.jpg
Tạo: Download_Images\japan2\1016\Q11649298_bright.jpg
Tạo: Download_Images\japan2\1016\Q11649298_noise.jpg
Tạo: Download_Images\japan2\1017\Q4121026_flip.jpg
Tạo: Download_Images\japan2\1017\Q4121026_rot-15.jpg
Tạo: Download_Images\japan2\1017\Q4121026_rot15.jpg
Tạo: Download_Images\japan2\1017\Q4121026_bright.jpg
Tạo: Download_Images\japan2\1017\Q4121026_noise.jpg
Tạo: Download_Images\japan2\1018\Q11470671_flip.jpg
Tạo: Download_Images\japan2\1018\Q11470671_rot-15.jpg
Tạo: Download_Images\japan2\1018\Q11470671_rot15.jpg
Tạo: Download_Images\japan2\1018\Q11470671_bright.jpg
Tạo: Download_Images\japan2\1018\Q11470671_noise.jpg
Tạo: Download_Images\japan2\1019\Q529825_flip.jpg
Tạo: Download_Images\japan2\1019\Q529825_rot-15.jpg
Tạo: Download_Images\japan2\1019\Q529825_rot15.jpg
Tạo: Download_Images\japan2\1019\Q529825_bright.jpg
Tạo: Download_Images\japan2\1019\Q529825_noise.jpg
Tạo: Download_Images\japan2\102\Q1055604_flip.jpg
Tạo: Download_Images\japan2\102\Q1055604_rot-15.jpg
Tạo: Download_Images\japan2\102\Q1055604_rot15.jpg
Tạo: Download_Images\japan2\102\Q1055604_bright.jpg
Tạo: Download_Images\japan2\102\Q1055604_noise.jpg
Tạo: Download_Images\japan2\1020\Q736403_flip.jpg
Tạo: Download_Images\japan2\1020\Q736403_rot-15.jpg
Tạo: Download_Images\japan2\1020\Q736403_rot15.jpg
Tạo: Download_Images\japan2\1020\Q736403_bright.jpg
Tạo: Download_Images\japan2\1020\Q736403_noise.jpg
Tạo: Download_Images\japan2\1021\Q11433740_flip.jpg
Tạo: Download_Images\japan2\1021\Q11433740_rot-15.jpg
Tạo: Download_Images\japan2\1021\Q11433740_rot15.jpg
Tạo: Download_Images\japan2\1021\Q11433740_bright.jpg
Tạo: Download_Images\japan2\1021\Q11433740_noise.jpg
Tạo: Download_Images\japan2\1022\Q11576512_flip.jpg
Tạo: Download_Images\japan2\1022\Q11576512_rot-15.jpg
Tạo: Download_Images\japan2\1022\Q11576512_rot15.jpg
Tạo: Download_Images\japan2\1022\Q11576512_bright.jpg
Tạo: Download_Images\japan2\1022\Q11576512_noise.jpg
Tạo: Download_Images\japan2\1023\Q11575296_flip.jpg
Tạo: Download_Images\japan2\1023\Q11575296_rot-15.jpg
Tạo: Download_Images\japan2\1023\Q11575296_rot15.jpg
Tạo: Download_Images\japan2\1023\Q11575296_bright.jpg
Tạo: Download_Images\japan2\1023\Q11575296_noise.jpg
Tạo: Download_Images\japan2\1024\Q11465889_flip.jpg
Tạo: Download_Images\japan2\1024\Q11465889_rot-15.jpg
Tạo: Download_Images\japan2\1024\Q11465889_rot15.jpg
Tạo: Download_Images\japan2\1024\Q11465889_bright.jpg
Tạo: Download_Images\japan2\1024\Q11465889_noise.jpg
Tạo: Download_Images\japan2\1025\Q1738770_flip.jpg
Tạo: Download_Images\japan2\1025\Q1738770_rot-15.jpg
Tạo: Download_Images\japan2\1025\Q1738770_rot15.jpg
Tạo: Download_Images\japan2\1025\Q1738770_bright.jpg
Tạo: Download_Images\japan2\1025\Q1738770_noise.jpg
Tạo: Download_Images\japan2\1026\Q537991_flip.jpg
Tạo: Download_Images\japan2\1026\Q537991_rot-15.jpg
Tạo: Download_Images\japan2\1026\Q537991_rot15.jpg
Tạo: Download_Images\japan2\1026\Q537991_bright.jpg
Tạo: Download_Images\japan2\1026\Q537991_noise.jpg
Tạo: Download_Images\japan2\1027\Q6389412_flip.jpg
Tạo: Download_Images\japan2\1027\Q6389412_rot-15.jpg
Tạo: Download_Images\japan2\1027\Q6389412_rot15.jpg
Tạo: Download_Images\japan2\1027\Q6389412_bright.jpg
Tạo: Download_Images\japan2\1027\Q6389412_noise.jpg
Tạo: Download_Images\japan2\1028\Q6391370_flip.jpg
Tạo: Download_Images\japan2\1028\Q6391370_rot-15.jpg
Tạo: Download_Images\japan2\1028\Q6391370_rot15.jpg
Tạo: Download_Images\japan2\1028\Q6391370_bright.jpg
Tạo: Download_Images\japan2\1028\Q6391370_noise.jpg
Tạo: Download_Images\japan2\1029\Q251768_flip.jpg
Tạo: Download_Images\japan2\1029\Q251768_rot-15.jpg
Tạo: Download_Images\japan2\1029\Q251768_rot15.jpg
Tạo: Download_Images\japan2\1029\Q251768_bright.jpg
Tạo: Download_Images\japan2\1029\Q251768_noise.jpg
Tạo: Download_Images\japan2\103\Q440006_flip.jpg
Tạo: Download_Images\japan2\103\Q440006_rot-15.jpg
Tạo: Download_Images\japan2\103\Q440006_rot15.jpg
Tạo: Download_Images\japan2\103\Q440006_bright.jpg
Tạo: Download_Images\japan2\103\Q440006_noise.jpg
Tạo: Download_Images\japan2\1030\Q21019128_flip.jpg
Tạo: Download_Images\japan2\1030\Q21019128_rot-15.jpg
Tạo: Download_Images\japan2\1030\Q21019128_rot15.jpg
Tạo: Download_Images\japan2\1030\Q21019128_bright.jpg
Tạo: Download_Images\japan2\1030\Q21019128_noise.jpg
Tạo: Download_Images\japan2\1031\Q1392655_flip.jpg
Tạo: Download_Images\japan2\1031\Q1392655_rot-15.jpg
Tạo: Download_Images\japan2\1031\Q1392655_rot15.jpg
Tạo: Download_Images\japan2\1031\Q1392655_bright.jpg
Tạo: Download_Images\japan2\1031\Q1392655_noise.jpg
Tạo: Download_Images\japan2\1032\Q2363614_flip.jpg
Tạo: Download_Images\japan2\1032\Q2363614_rot-15.jpg
Tạo: Download_Images\japan2\1032\Q2363614_rot15.jpg
Tạo: Download_Images\japan2\1032\Q2363614_bright.jpg
Tạo: Download_Images\japan2\1032\Q2363614_noise.jpg
Tạo: Download_Images\japan2\1033\Q923428_flip.jpg
Tạo: Download_Images\japan2\1033\Q923428_rot-15.jpg
Tạo: Download_Images\japan2\1033\Q923428_rot15.jpg
Tạo: Download_Images\japan2\1033\Q923428_bright.jpg
Tạo: Download_Images\japan2\1033\Q923428_noise.jpg
Tạo: Download_Images\japan2\1034\Q11529497_flip.jpg
Tạo: Download_Images\japan2\1034\Q11529497_rot-15.jpg
Tạo: Download_Images\japan2\1034\Q11529497_rot15.jpg
Tạo: Download_Images\japan2\1034\Q11529497_bright.jpg
Tạo: Download_Images\japan2\1034\Q11529497_noise.jpg
Tạo: Download_Images\japan2\1035\Q2153463_flip.jpg
Tạo: Download_Images\japan2\1035\Q2153463_rot-15.jpg
Tạo: Download_Images\japan2\1035\Q2153463_rot15.jpg
Tạo: Download_Images\japan2\1035\Q2153463_bright.jpg
Tạo: Download_Images\japan2\1035\Q2153463_noise.jpg
Tạo: Download_Images\japan2\1036\Q1739045_flip.jpg
Tạo: Download_Images\japan2\1036\Q1739045_rot-15.jpg
Tạo: Download_Images\japan2\1036\Q1739045_rot15.jpg
Tạo: Download_Images\japan2\1036\Q1739045_bright.jpg
Tạo: Download_Images\japan2\1036\Q1739045_noise.jpg
Tạo: Download_Images\japan2\1037\Q6391997_flip.jpg
Tạo: Download_Images\japan2\1037\Q6391997_rot-15.jpg
Tạo: Download_Images\japan2\1037\Q6391997_rot15.jpg
Tạo: Download_Images\japan2\1037\Q6391997_bright.jpg
Tạo: Download_Images\japan2\1037\Q6391997_noise.jpg
Tạo: Download_Images\japan2\1038\Q11369207_flip.jpg
Tạo: Download_Images\japan2\1038\Q11369207_rot-15.jpg
Tạo: Download_Images\japan2\1038\Q11369207_rot15.jpg
Tạo: Download_Images\japan2\1038\Q11369207_bright.jpg
Tạo: Download_Images\japan2\1038\Q11369207_noise.jpg
Tạo: Download_Images\japan2\1039\Q195582_flip.jpg
Tạo: Download_Images\japan2\1039\Q195582_rot-15.jpg
Tạo: Download_Images\japan2\1039\Q195582_rot15.jpg
Tạo: Download_Images\japan2\1039\Q195582_bright.jpg
Tạo: Download_Images\japan2\1039\Q195582_noise.jpg
Tạo: Download_Images\japan2\104\Q45207_flip.jpg
Tạo: Download_Images\japan2\104\Q45207_rot-15.jpg
Tạo: Download_Images\japan2\104\Q45207_rot15.jpg
Tạo: Download_Images\japan2\104\Q45207_bright.jpg
Tạo: Download_Images\japan2\104\Q45207_noise.jpg
Tạo: Download_Images\japan2\1040\Q17158653_flip.jpg
Tạo: Download_Images\japan2\1040\Q17158653_rot-15.jpg
Tạo: Download_Images\japan2\1040\Q17158653_rot15.jpg
Tạo: Download_Images\japan2\1040\Q17158653_bright.jpg
Tạo: Download_Images\japan2\1040\Q17158653_noise.jpg
Tạo: Download_Images\japan2\1041\Q1965622_flip.jpg
Tạo: Download_Images\japan2\1041\Q1965622_rot-15.jpg
Tạo: Download_Images\japan2\1041\Q1965622_rot15.jpg
Tạo: Download_Images\japan2\1041\Q1965622_bright.jpg
Tạo: Download_Images\japan2\1041\Q1965622_noise.jpg
Tạo: Download_Images\japan2\1042\Q17160475_flip.jpg
Tạo: Download_Images\japan2\1042\Q17160475_rot-15.jpg
Tạo: Download_Images\japan2\1042\Q17160475_rot15.jpg
Tạo: Download_Images\japan2\1042\Q17160475_bright.jpg
Tạo: Download_Images\japan2\1042\Q17160475_noise.jpg
Tạo: Download_Images\japan2\1043\Q11478659_flip.jpg
Tạo: Download_Images\japan2\1043\Q11478659_rot-15.jpg
Tạo: Download_Images\japan2\1043\Q11478659_rot15.jpg
Tạo: Download_Images\japan2\1043\Q11478659_bright.jpg
Tạo: Download_Images\japan2\1043\Q11478659_noise.jpg
Tạo: Download_Images\japan2\1044\Q18054827_flip.jpg
Tạo: Download_Images\japan2\1044\Q18054827_rot-15.jpg
Tạo: Download_Images\japan2\1044\Q18054827_rot15.jpg
Tạo: Download_Images\japan2\1044\Q18054827_bright.jpg
Tạo: Download_Images\japan2\1044\Q18054827_noise.jpg
Tạo: Download_Images\japan2\1045\Q11365308_flip.jpg
Tạo: Download_Images\japan2\1045\Q11365308_rot-15.jpg
Tạo: Download_Images\japan2\1045\Q11365308_rot15.jpg
Tạo: Download_Images\japan2\1045\Q11365308_bright.jpg
Tạo: Download_Images\japan2\1045\Q11365308_noise.jpg
Tạo: Download_Images\japan2\1046\Q1739068_flip.jpg
Tạo: Download_Images\japan2\1046\Q1739068_rot-15.jpg
Tạo: Download_Images\japan2\1046\Q1739068_rot15.jpg
Tạo: Download_Images\japan2\1046\Q1739068_bright.jpg
Tạo: Download_Images\japan2\1046\Q1739068_noise.jpg
Tạo: Download_Images\japan2\1047\Q49996_flip.jpg
Tạo: Download_Images\japan2\1047\Q49996_rot-15.jpg
Tạo: Download_Images\japan2\1047\Q49996_rot15.jpg
Tạo: Download_Images\japan2\1047\Q49996_bright.jpg
Tạo: Download_Images\japan2\1047\Q49996_noise.jpg
Tạo: Download_Images\japan2\1048\Q973509_flip.jpg
Tạo: Download_Images\japan2\1048\Q973509_rot-15.jpg
Tạo: Download_Images\japan2\1048\Q973509_rot15.jpg
Tạo: Download_Images\japan2\1048\Q973509_bright.jpg
Tạo: Download_Images\japan2\1048\Q973509_noise.jpg
Tạo: Download_Images\japan2\1049\Q17686812_flip.jpg
Tạo: Download_Images\japan2\1049\Q17686812_rot-15.jpg
Tạo: Download_Images\japan2\1049\Q17686812_rot15.jpg
Tạo: Download_Images\japan2\1049\Q17686812_bright.jpg
Tạo: Download_Images\japan2\1049\Q17686812_noise.jpg
Tạo: Download_Images\japan2\105\Q4778607_flip.jpg
Tạo: Download_Images\japan2\105\Q4778607_rot-15.jpg
Tạo: Download_Images\japan2\105\Q4778607_rot15.jpg
Tạo: Download_Images\japan2\105\Q4778607_bright.jpg
Tạo: Download_Images\japan2\105\Q4778607_noise.jpg
Tạo: Download_Images\japan2\1050\Q2093536_flip.jpg
Tạo: Download_Images\japan2\1050\Q2093536_rot-15.jpg
Tạo: Download_Images\japan2\1050\Q2093536_rot15.jpg
Tạo: Download_Images\japan2\1050\Q2093536_bright.jpg
Tạo: Download_Images\japan2\1050\Q2093536_noise.jpg
Tạo: Download_Images\japan2\1051\Q15044007_flip.jpg
Tạo: Download_Images\japan2\1051\Q15044007_rot-15.jpg
Tạo: Download_Images\japan2\1051\Q15044007_rot15.jpg
Tạo: Download_Images\japan2\1051\Q15044007_bright.jpg
Tạo: Download_Images\japan2\1051\Q15044007_noise.jpg
Tạo: Download_Images\japan2\1052\Q2342896_flip.jpg
Tạo: Download_Images\japan2\1052\Q2342896_rot-15.jpg
Tạo: Download_Images\japan2\1052\Q2342896_rot15.jpg
Tạo: Download_Images\japan2\1052\Q2342896_bright.jpg
Tạo: Download_Images\japan2\1052\Q2342896_noise.jpg
Tạo: Download_Images\japan2\1053\Q21946854_flip.jpg
Tạo: Download_Images\japan2\1053\Q21946854_rot-15.jpg
Tạo: Download_Images\japan2\1053\Q21946854_rot15.jpg
Tạo: Download_Images\japan2\1053\Q21946854_bright.jpg
Tạo: Download_Images\japan2\1053\Q21946854_noise.jpg
Tạo: Download_Images\japan2\1054\Q850695_flip.jpg
Tạo: Download_Images\japan2\1054\Q850695_rot-15.jpg
Tạo: Download_Images\japan2\1054\Q850695_rot15.jpg
Tạo: Download_Images\japan2\1054\Q850695_bright.jpg
Tạo: Download_Images\japan2\1054\Q850695_noise.jpg
Tạo: Download_Images\japan2\1055\Q997647_flip.jpg
Tạo: Download_Images\japan2\1055\Q997647_rot-15.jpg
Tạo: Download_Images\japan2\1055\Q997647_rot15.jpg
Tạo: Download_Images\japan2\1055\Q997647_bright.jpg
Tạo: Download_Images\japan2\1055\Q997647_noise.jpg
Tạo: Download_Images\japan2\1056\Q18235356_flip.jpg
Tạo: Download_Images\japan2\1056\Q18235356_rot-15.jpg
Tạo: Download_Images\japan2\1056\Q18235356_rot15.jpg
Tạo: Download_Images\japan2\1056\Q18235356_bright.jpg
Tạo: Download_Images\japan2\1056\Q18235356_noise.jpg
Tạo: Download_Images\japan2\1057\Q11522361_flip.jpg
Tạo: Download_Images\japan2\1057\Q11522361_rot-15.jpg
Tạo: Download_Images\japan2\1057\Q11522361_rot15.jpg
Tạo: Download_Images\japan2\1057\Q11522361_bright.jpg
Tạo: Download_Images\japan2\1057\Q11522361_noise.jpg
Tạo: Download_Images\japan2\1058\Q20036558_flip.jpg
Tạo: Download_Images\japan2\1058\Q20036558_rot-15.jpg
Tạo: Download_Images\japan2\1058\Q20036558_rot15.jpg
Tạo: Download_Images\japan2\1058\Q20036558_bright.jpg
Tạo: Download_Images\japan2\1058\Q20036558_noise.jpg
Tạo: Download_Images\japan2\1059\Q232636_flip.jpg
Tạo: Download_Images\japan2\1059\Q232636_rot-15.jpg
Tạo: Download_Images\japan2\1059\Q232636_rot15.jpg
Tạo: Download_Images\japan2\1059\Q232636_bright.jpg
Tạo: Download_Images\japan2\1059\Q232636_noise.jpg
Tạo: Download_Images\japan2\106\Q11586706_flip.jpg
Tạo: Download_Images\japan2\106\Q11586706_rot-15.jpg
Tạo: Download_Images\japan2\106\Q11586706_rot15.jpg
Tạo: Download_Images\japan2\106\Q11586706_bright.jpg
Tạo: Download_Images\japan2\106\Q11586706_noise.jpg
Tạo: Download_Images\japan2\1060\Q11410189_flip.jpg
Tạo: Download_Images\japan2\1060\Q11410189_rot-15.jpg
Tạo: Download_Images\japan2\1060\Q11410189_rot15.jpg
Tạo: Download_Images\japan2\1060\Q11410189_bright.jpg
Tạo: Download_Images\japan2\1060\Q11410189_noise.jpg
Tạo: Download_Images\japan2\1061\Q6410130_flip.jpg
Tạo: Download_Images\japan2\1061\Q6410130_rot-15.jpg
Tạo: Download_Images\japan2\1061\Q6410130_rot15.jpg
Tạo: Download_Images\japan2\1061\Q6410130_bright.jpg
Tạo: Download_Images\japan2\1061\Q6410130_noise.jpg
Tạo: Download_Images\japan2\1062\Q26236286_flip.jpg
Tạo: Download_Images\japan2\1062\Q26236286_rot-15.jpg
Tạo: Download_Images\japan2\1062\Q26236286_rot15.jpg
Tạo: Download_Images\japan2\1062\Q26236286_bright.jpg
Tạo: Download_Images\japan2\1062\Q26236286_noise.jpg
Tạo: Download_Images\japan2\1063\Q17989782_flip.jpg
Tạo: Download_Images\japan2\1063\Q17989782_rot-15.jpg
Tạo: Download_Images\japan2\1063\Q17989782_rot15.jpg
Tạo: Download_Images\japan2\1063\Q17989782_bright.jpg
Tạo: Download_Images\japan2\1063\Q17989782_noise.jpg
Tạo: Download_Images\japan2\1064\Q5975489_flip.jpg
Tạo: Download_Images\japan2\1064\Q5975489_rot-15.jpg
Tạo: Download_Images\japan2\1064\Q5975489_rot15.jpg
Tạo: Download_Images\japan2\1064\Q5975489_bright.jpg
Tạo: Download_Images\japan2\1064\Q5975489_noise.jpg
Tạo: Download_Images\japan2\1065\Q11487010_flip.jpg
Tạo: Download_Images\japan2\1065\Q11487010_rot-15.jpg
Tạo: Download_Images\japan2\1065\Q11487010_rot15.jpg
Tạo: Download_Images\japan2\1065\Q11487010_bright.jpg
Tạo: Download_Images\japan2\1065\Q11487010_noise.jpg
Tạo: Download_Images\japan2\1066\Q4220702_flip.jpg
Tạo: Download_Images\japan2\1066\Q4220702_rot-15.jpg
Tạo: Download_Images\japan2\1066\Q4220702_rot15.jpg
Tạo: Download_Images\japan2\1066\Q4220702_bright.jpg
Tạo: Download_Images\japan2\1066\Q4220702_noise.jpg
Tạo: Download_Images\japan2\1067\Q3548276_flip.jpg
Tạo: Download_Images\japan2\1067\Q3548276_rot-15.jpg
Tạo: Download_Images\japan2\1067\Q3548276_rot15.jpg

In [6]:
import os
import cv2
import shutil
import stat

# Đường dẫn tuyệt đối đến thư mục japan2
root_dir = r"C:\Users\DELL\OneDrive\Documents\FaceDetection\Download_Images\japan2"

# Load Haar Cascade
cascade_path = 'haarcascade_frontalface_default.xml'
face_cascade = cv2.CascadeClassifier(cascade_path)
if face_cascade.empty():
    raise FileNotFoundError(f"Không tìm thấy file Haar Cascade tại: {cascade_path}")

def _handle_remove_readonly(func, path, exc_info):
    """
    Callback để bỏ chế độ read-only và thử lại.
    """
    # Đặt lại quyền write cho file/folder
    os.chmod(path, stat.S_IWRITE)
    # Gọi lại chính hàm đã lỗi (os.remove hoặc os.rmdir)
    func(path)

def remove_folders_with_no_faces(root_directory):
    for label in os.listdir(root_directory):
        folder_path = os.path.join(root_directory, label)
        if not os.path.isdir(folder_path):
            continue

        jpgs = [f for f in os.listdir(folder_path) if f.lower().endswith('.jpg')]
        if not jpgs:
            continue

        no_face = 0
        for fn in jpgs:
            img = cv2.imread(os.path.join(folder_path, fn))
            if img is None:
                no_face += 1
                continue
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            faces = face_cascade.detectMultiScale(gray,
                                                  scaleFactor=1.1,
                                                  minNeighbors=5,
                                                  minSize=(30, 30),
                                                  flags=cv2.CASCADE_SCALE_IMAGE)
            if len(faces) == 0:
                no_face += 1

        if no_face == len(jpgs):
            # Dùng onerror để tự động bỏ readonly và xóa
            shutil.rmtree(folder_path, onerror=_handle_remove_readonly)

if __name__ == '__main__':
    # Nếu cần chạy với quyền cao hơn, hãy mở cmd/PowerShell as Admin
    remove_folders_with_no_faces(root_dir)

In [3]:
import os
import shutil
import random
from pathlib import Path

# --- CẤU HÌNH ---
# Thư mục gốc chứa dữ liệu gốc với các thư mục con là tên từng người
src_root = Path(r"C:\Users\DELL\OneDrive\Documents\FaceDetection\Download_Images\japan2")
# Thư mục đích chứa kết quả Split
dst_root = src_root.parent / "SplitData_by_person"
# Tỉ lệ chia: train, validation, test
split_ratio = {"train": 0.8, "val": 0.1, "test": 0.1}

# Hàm chia dữ liệu theo thư mục người (identity-level split)
def split_by_person(src_root: Path, dst_root: Path, ratio: dict):
    # Lấy danh sách các thư mục con (mỗi thư mục là toàn bộ ảnh của một người)
    persons = [d for d in src_root.iterdir() if d.is_dir()]
    if not persons:
        print(f"Không tìm thấy thư mục con trong {src_root}")
        return

    # Trộn ngẫu nhiên danh sách thư mục người
    random.shuffle(persons)

    # Tính số lượng folder cho từng tập
    total = len(persons)
    n_train = int(total * ratio['train'])
    n_val = int(total * ratio['val'])
    n_test = total - n_train - n_val

    splits = {
        'train': persons[:n_train],
        'val': persons[n_train:n_train + n_val],
        'test': persons[n_train + n_val:]
    }

    # Copy nguyên thư mục mỗi người vào tập tương ứng
    for split_name, person_dirs in splits.items():
        for person_dir in person_dirs:
            target_dir = dst_root / split_name / person_dir.name
            # Copy toàn bộ folder và file con
            shutil.copytree(person_dir, target_dir)
            print(f"Copied {person_dir.name} to {split_name}")

    print(f"Hoàn tất: dữ liệu chia theo thư mục người đã lưu tại {dst_root}")


if __name__ == '__main__':
    # Tạo thư mục đích nếu chưa có
    dst_root.mkdir(parents=True, exist_ok=True)
    split_by_person(src_root, dst_root, split_ratio)

Copied 1143 to train
Copied 185 to train
Copied 1467 to train
Copied 2017 to train
Copied 1815 to train
Copied 3022 to train
Copied 1578 to train
Copied 2130 to train
Copied 2309 to train
Copied 764 to train
Copied 2314 to train
Copied 983 to train
Copied 2344 to train
Copied 1435 to train
Copied 1058 to train
Copied 1141 to train
Copied 1579 to train
Copied 2194 to train
Copied 1802 to train
Copied 842 to train
Copied 1681 to train
Copied 476 to train
Copied 2345 to train
Copied 50 to train
Copied 576 to train
Copied 164 to train
Copied 557 to train
Copied 1743 to train
Copied 2651 to train
Copied 2268 to train
Copied 1179 to train
Copied 1751 to train
Copied 2176 to train
Copied 1531 to train
Copied 1428 to train
Copied 406 to train
Copied 189 to train
Copied 2374 to train
Copied 51 to train
Copied 1884 to train
Copied 1722 to train
Copied 2519 to train
Copied 2042 to train
Copied 2674 to train
Copied 2760 to train
Copied 1717 to train
Copied 2761 to train
Copied 1423 to train
Copied 2790 to train
Copied 603 to train
Copied 32 to train
Copied 696 to train
Copied 1547 to train
Copied 2788 to train
Copied 1817 to train
Copied 595 to train
Copied 2919 to train
Copied 834 to train
Copied 212 to train
Copied 89 to train
Copied 2675 to train
Copied 2189 to train
Copied 1086 to train
Copied 246 to train
Copied 2666 to train
Copied 281 to train
Copied 2642 to train
Copied 483 to train
Copied 2143 to train
Copied 1764 to train
Copied 1229 to train
Copied 1841 to train
Copied 1527 to train
Copied 2640 to train
Copied 2044 to train
Copied 2306 to train
Copied 706 to train
Copied 1436 to train
Copied 896 to train
Copied 2986 to train
Copied 1111 to train
Copied 2010 to train
Copied 1211 to train
Copied 3027 to train
Copied 2926 to train
Copied 760 to train
Copied 2139 to train
Copied 2929 to train
Copied 587 to train
Copied 3 to train
Copied 821 to train
Copied 486 to train
Copied 2127 to train
Copied 2776 to train
Copied 40 to train
Copied 1634 to train
Copied 1647 to train
Copied 2531 to train
Copied 261 to train
Copied 2258 to train
Copied 351 to train
Copied 191 to train
Copied 2872 to train
Copied 1921 to train
Copied 394 to train
Copied 1856 to train
Copied 1035 to train
Copied 2473 to train
Copied 1788 to train
Copied 2073 to train
Copied 3025 to train
Copied 2217 to train
Copied 3026 to train
Copied 404 to train
Copied 1528 to train
Copied 1611 to train
Copied 1845 to train
Copied 2330 to train
Copied 2787 to train
Copied 646 to train
Copied 81 to train
Copied 651 to train
Copied 2225 to train
Copied 3012 to train
Copied 464 to train
Copied 1039 to train
Copied 871 to train
Copied 1863 to train
Copied 1437 to train
Copied 902 to train
Copied 280 to train
Copied 2223 to train
Copied 1982 to train
Copied 1999 to train
Copied 1061 to train
Copied 981 to train
Copied 434 to train
Copied 1998 to train
Copied 137 to train
Copied 1741 to train
Copied 269 to train
Copied 543 to train
Copied 771 to train
Copied 425 to train
Copied 685 to train
Copied 1214 to train
Copied 624 to train
Copied 2388 to train
Copied 323 to train
Copied 1724 to train
Copied 3067 to train
Copied 1973 to train
Copied 105 to train
Copied 2254 to train
Copied 640 to train
Copied 2082 to train
Copied 912 to train
Copied 2500 to train
Copied 1804 to train
Copied 2784 to train
Copied 2372 to train
Copied 763 to train
Copied 632 to train
Copied 53 to train
Copied 1286 to train
Copied 61 to train
Copied 2741 to train
Copied 279 to train
Copied 2477 to train
Copied 720 to train
Copied 1525 to train
Copied 2346 to train
Copied 1742 to train
Copied 1736 to train
Copied 649 to train
Copied 273 to train
Copied 1064 to train
Copied 1414 to train
Copied 514 to train
Copied 1604 to train
Copied 694 to train
Copied 3065 to train
Copied 2548 to train
Copied 2468 to train
Copied 358 to train
Copied 719 to train
Copied 1990 to train
Copied 1452 to train
Copied 1721 to train
Copied 60 to train
Copied 731 to train
Copied 1864 to train
Copied 75 to train
Copied 218 to train
Copied 1765 to train
Copied 1130 to train
Copied 947 to train
Copied 1753 to train
Copied 1254 to train
Copied 278 to train
Copied 481 to train
Copied 426 to train
Copied 1960 to train
Copied 2246 to train
Copied 2685 to train
Copied 2302 to train
Copied 2636 to train
Copied 1314 to train
Copied 1092 to train
Copied 374 to train
Copied 70 to train
Copied 208 to train
Copied 1546 to train
Copied 1060 to train
Copied 1355 to train
Copied 207 to train
Copied 2815 to train
Copied 3071 to train
Copied 628 to train
Copied 1935 to train
Copied 2102 to train
Copied 202 to train
Copied 2601 to train
Copied 3000 to train
Copied 371 to train
Copied 1984 to train
Copied 1759 to train
Copied 378 to train
Copied 816 to train
Copied 736 to train
Copied 601 to train
Copied 2859 to train
Copied 968 to train
Copied 2612 to train
Copied 438 to train
Copied 1644 to train
Copied 100 to train
Copied 2379 to train
Copied 353 to train
Copied 2226 to train
Copied 1875 to train
Copied 898 to train
Copied 2285 to train
Copied 2293 to train
Copied 3033 to train
Copied 613 to train
Copied 2715 to train
Copied 2917 to train
Copied 1393 to train
Copied 3059 to train
Copied 765 to train
Copied 1891 to train
Copied 1102 to train
Copied 2676 to train
Copied 1496 to train
Copied 1439 to train
Copied 1432 to train
Copied 1584 to train
Copied 872 to train
Copied 2821 to train
Copied 390 to train
Copied 2367 to train
Copied 2011 to train
Copied 883 to train
Copied 1104 to train
Copied 1778 to train
Copied 128 to train
Copied 1893 to train
Copied 1709 to train
Copied 2810 to train
Copied 676 to train
Copied 1687 to train
Copied 2316 to train
Copied 1482 to train
Copied 383 to train
Copied 553 to train
Copied 102 to train
Copied 1569 to train
Copied 2040 to train
Copied 2828 to train
Copied 1614 to train
Copied 1559 to train
Copied 1758 to train
Copied 2751 to train
Copied 84 to train
Copied 864 to train
Copied 173 to train
Copied 2556 to train
Copied 1402 to train
Copied 841 to train
Copied 548 to train
Copied 263 to train
Copied 2256 to train
Copied 1109 to train
Copied 482 to train
Copied 2370 to train
Copied 336 to train
Copied 1259 to train
Copied 1526 to train
Copied 2085 to train
Copied 2566 to train
Copied 1114 to train
Copied 732 to train
Copied 2555 to train
Copied 1353 to train
Copied 663 to train
Copied 1471 to train
Copied 432 to train
Copied 2406 to train
Copied 989 to train
Copied 1651 to train
Copied 2974 to train
Copied 2518 to train
Copied 2208 to train
Copied 484 to train
Copied 2028 to train
Copied 1732 to train
Copied 2934 to train
Copied 1140 to train
Copied 1602 to train
Copied 2264 to train
Copied 2838 to train
Copied 3017 to train
Copied 728 to train
Copied 1040 to train
Copied 2671 to train
Copied 561 to train
Copied 2466 to train
Copied 1292 to train
Copied 1195 to train
Copied 2352 to train
Copied 123 to train
Copied 211 to train
Copied 2753 to train
Copied 1065 to train
Copied 2996 to train
Copied 937 to train
Copied 2324 to train
Copied 1189 to train
Copied 225 to train
Copied 38 to train
Copied 657 to train
Copied 531 to train
Copied 516 to train
Copied 1485 to train
Copied 294 to train
Copied 1657 to train
Copied 862 to train
Copied 1907 to train
Copied 1080 to train
Copied 1239 to train
Copied 940 to train
Copied 2542 to train
Copied 2318 to train
Copied 2993 to train
Copied 2670 to train
Copied 639 to train
Copied 2151 to train
Copied 1328 to train
Copied 2464 to train
Copied 709 to train
Copied 2918 to train
Copied 1479 to train
Copied 1449 to train
Copied 1473 to train
Copied 449 to train
Copied 2170 to train
Copied 629 to train
Copied 47 to train
Copied 2283 to train
Copied 2218 to train
Copied 2575 to train
Copied 2605 to train
Copied 874 to train
Copied 2474 to train
Copied 592 to train
Copied 2141 to train
Copied 2839 to train
Copied 1606 to train
Copied 2569 to train
Copied 36 to train
Copied 1090 to train
Copied 1669 to train
Copied 2012 to train
Copied 2876 to train
Copied 1240 to train
Copied 140 to train
Copied 1474 to train
Copied 809 to train
Copied 2922 to train
Copied 1739 to train
Copied 2647 to train
Copied 1020 to train
Copied 522 to train
Copied 3051 to train
Copied 563 to train
Copied 2960 to train
Copied 2460 to train
Copied 1484 to train
Copied 62 to train
Copied 2442 to train
Copied 346 to train
Copied 1050 to train
Copied 2160 to train
Copied 949 to train
Copied 2340 to train
Copied 1320 to train
Copied 846 to train
Copied 267 to train
Copied 812 to train
Copied 52 to train
Copied 2683 to train
Copied 759 to train
Copied 3044 to train
Copied 717 to train
Copied 1183 to train
Copied 797 to train
Copied 2484 to train
Copied 2802 to train
Copied 28 to train
Copied 253 to train
Copied 2461 to train
Copied 250 to train
Copied 49 to train
Copied 773 to train
Copied 2273 to train
Copied 1288 to train
Copied 1748 to train
Copied 1115 to train
Copied 2013 to train
Copied 910 to train
Copied 1682 to train
Copied 2124 to train
Copied 2726 to train
Copied 39 to train
Copied 638 to train
Copied 2710 to train
Copied 2317 to train
Copied 3015 to train
Copied 1224 to train
Copied 777 to train
Copied 1356 to train
Copied 387 to train
Copied 1453 to train
Copied 2527 to train
Copied 442 to train
Copied 2576 to train
Copied 1766 to train
Copied 537 to train
Copied 721 to train
Copied 873 to train
Copied 2879 to train
Copied 2105 to train
Copied 2322 to train
Copied 1663 to train
Copied 197 to train
Copied 870 to train
Copied 2410 to train
Copied 48 to train
Copied 3040 to train
Copied 2212 to train
Copied 179 to train
Copied 2832 to train
Copied 1598 to train
Copied 458 to train
Copied 2769 to train
Copied 290 to train
Copied 697 to train
Copied 2515 to train
Copied 1775 to train
Copied 1150 to train
Copied 2375 to train
Copied 1991 to train
Copied 2963 to train
Copied 96 to train
Copied 493 to train
Copied 86 to train
Copied 1478 to train
Copied 1843 to train
Copied 1041 to train
Copied 508 to train
Copied 1342 to train
Copied 2286 to train
Copied 265 to train
Copied 1906 to train
Copied 77 to train
Copied 680 to train
Copied 2851 to train
Copied 1694 to train
Copied 1160 to train
Copied 344 to train
Copied 2632 to train
Copied 2156 to train
Copied 1889 to train
Copied 1599 to train
Copied 2718 to train
Copied 143 to train
Copied 103 to train
Copied 1327 to train
Copied 878 to train
Copied 944 to train
Copied 1842 to train
Copied 714 to train
Copied 1362 to train
Copied 1124 to train
Copied 2029 to train
Copied 1219 to train
Copied 2272 to train
Copied 955 to train
Copied 1618 to train
Copied 2942 to train
Copied 1530 to train
Copied 1221 to train
Copied 2005 to train
Copied 1075 to train
Copied 2947 to train
Copied 1131 to train
Copied 985 to train
Copied 899 to train
Copied 2506 to train
Copied 1332 to train
Copied 2528 to train
Copied 375 to train
Copied 2337 to train
Copied 1894 to train
Copied 2205 to train
Copied 2924 to train
Copied 963 to train
Copied 627 to train
Copied 528 to train
Copied 83 to train
Copied 2440 to train
Copied 529 to train
Copied 501 to train
Copied 1330 to train
Copied 904 to train
Copied 1600 to train
Copied 467 to train
Copied 1352 to train
Copied 2661 to train
Copied 961 to train
Copied 735 to train
Copied 1674 to train
Copied 2015 to train
Copied 1821 to train
Copied 108 to train
Copied 1106 to train
Copied 644 to train
Copied 2890 to train
Copied 373 to train
Copied 2522 to train
Copied 2201 to train
Copied 814 to train
Copied 3013 to train
Copied 2496 to train
Copied 1345 to train
Copied 286 to train
Copied 2957 to train
Copied 2875 to train
Copied 1964 to train
Copied 948 to train
Copied 2733 to train
Copied 1483 to train
Copied 726 to train
Copied 2629 to train
Copied 421 to train
Copied 376 to train
Copied 1381 to train
Copied 875 to train
Copied 2962 to train
Copied 2564 to train
Copied 2931 to train
Copied 1958 to train
Copied 2150 to train
Copied 1622 to train
Copied 869 to train
Copied 206 to train
Copied 1374 to train
Copied 1329 to train
Copied 2654 to train
Copied 1747 to train
Copied 1268 to train
Copied 126 to train
Copied 894 to train
Copied 1834 to train
Copied 1494 to train
Copied 221 to train
Copied 758 to train
Copied 956 to train
Copied 2807 to train
Copied 2136 to train
Copied 782 to train
Copied 2228 to train
Copied 2973 to train
Copied 774 to train
Copied 1048 to train
Copied 877 to train
Copied 2088 to train
Copied 1979 to train
Copied 1197 to train
Copied 2118 to train
Copied 276 to train
Copied 1022 to train
Copied 1946 to train
Copied 1619 to train
Copied 1379 to train
Copied 2852 to train
Copied 3052 to train
Copied 23 to train
Copied 1833 to train
Copied 1652 to train
Copied 1348 to train
Copied 858 to train
Copied 68 to train
Copied 1201 to train
Copied 1142 to train
Copied 2069 to train
Copied 1582 to train
Copied 1007 to train
Copied 2920 to train
Copied 1548 to train
Copied 811 to train
Copied 234 to train
Copied 1703 to train
Copied 2722 to train
Copied 495 to train
Copied 400 to train
Copied 403 to train
Copied 98 to train
Copied 1032 to train
Copied 3061 to train
Copied 551 to train
Copied 1985 to train
Copied 666 to train
Copied 880 to train
Copied 389 to train
Copied 819 to train
Copied 756 to train
Copied 2291 to train
Copied 2591 to train
Copied 645 to train
Copied 2287 to train
Copied 1053 to train
Copied 2698 to train
Copied 1612 to train
Copied 107 to train
Copied 2639 to train
Copied 1831 to train
Copied 1468 to train
Copied 2743 to train
Copied 2695 to train
Copied 2829 to train
Copied 1210 to train
Copied 1170 to train
Copied 2691 to train
Copied 943 to train
Copied 184 to train
Copied 1783 to train
Copied 1795 to train
Copied 2067 to train
Copied 503 to train
Copied 1805 to train
Copied 2762 to train
Copied 526 to train
Copied 478 to train
Copied 838 to train
Copied 2068 to train
Copied 2735 to train
Copied 1271 to train
Copied 1253 to train
Copied 996 to train
Copied 2404 to train
Copied 1738 to train
Copied 635 to train
Copied 2321 to train
Copied 817 to train
Copied 298 to train
Copied 430 to train
Copied 2795 to train
Copied 1676 to train
Copied 424 to train
Copied 1511 to train
Copied 480 to train
Copied 2961 to train
Copied 1334 to train
Copied 2561 to train
Copied 2709 to train
Copied 1025 to train
Copied 807 to train
Copied 170 to train
Copied 2820 to train
Copied 1879 to train
Copied 713 to train
Copied 1873 to train
Copied 1545 to train
Copied 2276 to train
Copied 1574 to train
Copied 2055 to train
Copied 1389 to train
Copied 1992 to train
Copied 3060 to train
Copied 2260 to train
Copied 2296 to train
Copied 790 to train
Copied 226 to train
Copied 1101 to train
Copied 1779 to train
Copied 2530 to train
Copied 2860 to train
Copied 1267 to train
Copied 815 to train
Copied 2703 to train
Copied 2782 to train
Copied 536 to train
Copied 120 to train
Copied 2301 to train
Copied 1523 to train
Copied 85 to train
Copied 2099 to train
Copied 2600 to train
Copied 359 to train
Copied 2801 to train
Copied 1462 to train
Copied 2459 to train
Copied 2420 to train
Copied 3021 to train
Copied 833 to train
Copied 124 to train
Copied 153 to train
Copied 1318 to train
Copied 2604 to train
Copied 193 to train
Copied 1459 to train
Copied 1828 to train
Copied 1365 to train
Copied 73 to train
Copied 2565 to train
Copied 1970 to train
Copied 643 to train
Copied 2022 to train
Copied 1909 to train
Copied 2024 to train
Copied 2131 to train
Copied 2895 to train
Copied 2521 to train
Copied 2523 to train
Copied 1534 to train
Copied 2430 to train
Copied 2356 to train
Copied 2915 to train
Copied 2381 to train
Copied 1097 to train
Copied 490 to train
Copied 1122 to train
Copied 2452 to train
Copied 2583 to train
Copied 1498 to train
Copied 1307 to train
Copied 2202 to train
Copied 1073 to train
Copied 259 to train
Copied 428 to train
Copied 927 to train
Copied 2419 to train
Copied 654 to train
Copied 2159 to train
Copied 18 to train
Copied 567 to train
Copied 257 to train
Copied 979 to train
Copied 737 to train
Copied 1299 to train
Copied 133 to train
Copied 847 to train
Copied 1112 to train
Copied 957 to train
Copied 800 to train
Copied 1091 to train
Copied 1492 to train
Copied 1024 to train
Copied 2368 to train
Copied 1242 to train
Copied 689 to train
Copied 2668 to train
Copied 724 to train
Copied 565 to train
Copied 384 to train
Copied 733 to train
Copied 1198 to train
Copied 519 to train
Copied 157 to train
Copied 1084 to train
Copied 2222 to train
Copied 1495 to train
Copied 422 to train
Copied 2835 to train
Copied 2849 to train
Copied 37 to train
Copied 2705 to train
Copied 2580 to train
Copied 2646 to train
Copied 1051 to train
Copied 2387 to train
Copied 1697 to train
Copied 2373 to train
Copied 1940 to train
Copied 1983 to train
Copied 1945 to train
Copied 523 to train
Copied 1770 to train
Copied 3079 to train
Copied 2857 to train
Copied 1959 to train
Copied 634 to train
Copied 3010 to train
Copied 2326 to train
Copied 287 to train
Copied 1870 to train
Copied 151 to train
Copied 1646 to train
Copied 2711 to train
Copied 2084 to train
Copied 217 to train
Copied 2842 to train
Copied 2552 to train
Copied 572 to train
Copied 241 to train
Copied 1470 to train
Copied 1931 to train
Copied 2018 to train
Copied 1282 to train
Copied 860 to train
Copied 2008 to train
Copied 1561 to train
Copied 1580 to train
Copied 1608 to train
Copied 530 to train
Copied 2148 to train
Copied 1269 to train
Copied 1926 to train
Copied 582 to train
Copied 2083 to train
Copied 1626 to train
Copied 236 to train
Copied 3074 to train
Copied 485 to train
Copied 2707 to train
Copied 1799 to train
Copied 1306 to train
Copied 1878 to train
Copied 1343 to train
Copied 2850 to train
Copied 1415 to train
Copied 1862 to train
Copied 1018 to train
Copied 1592 to train
Copied 803 to train
Copied 667 to train
Copied 820 to train
Copied 411 to train
Copied 524 to train
Copied 977 to train
Copied 2311 to train
Copied 2826 to train
Copied 452 to train
Copied 13 to train
Copied 1014 to train
Copied 770 to train
Copied 2305 to train
Copied 1147 to train
Copied 684 to train
Copied 3004 to train
Copied 2597 to train
Copied 581 to train
Copied 1455 to train
Copied 183 to train
Copied 1597 to train
Copied 1347 to train
Copied 1593 to train
Copied 616 to train
Copied 1386 to train
Copied 2443 to train
Copied 187 to train
Copied 2128 to train
Copied 268 to train
Copied 2514 to train
Copied 1780 to train
Copied 3054 to train
Copied 1577 to train
Copied 818 to train
Copied 741 to train
Copied 2236 to train
Copied 762 to train
Copied 2185 to train
Copied 2900 to train
Copied 882 to train
Copied 1302 to train
Copied 420 to train
Copied 2284 to train
Copied 1311 to train
Copied 2886 to train
Copied 1887 to train
Copied 2231 to train
Copied 768 to train
Copied 2967 to train
Copied 2638 to train
Copied 2880 to train
Copied 1996 to train
Copied 787 to train
Copied 243 to train
Copied 1543 to train
Copied 674 to train
Copied 354 to train
Copied 2030 to train
Copied 1826 to train
Copied 853 to train
Copied 532 to train
Copied 1728 to train
Copied 1001 to train
Copied 1929 to train
Copied 1245 to train
Copied 1993 to train
Copied 1532 to train
Copied 879 to train
Copied 2001 to train
Copied 1358 to train
Copied 2785 to train
Copied 2065 to train
Copied 231 to train
Copied 2108 to train
Copied 3076 to train
Copied 959 to train
Copied 2990 to train
Copied 1284 to train
Copied 972 to train
Copied 2280 to train
Copied 1807 to train
Copied 2848 to train
Copied 798 to train
Copied 2554 to train
Copied 3014 to train
Copied 2989 to train
Copied 936 to train
Copied 593 to train
Copied 702 to train
Copied 984 to train
Copied 2717 to train
Copied 637 to train
Copied 1901 to train
Copied 1399 to train
Copied 168 to train
Copied 725 to train
Copied 326 to train
Copied 1594 to train
Copied 2615 to train
Copied 471 to train
Copied 1460 to train
Copied 1855 to train
Copied 2057 to train
Copied 1563 to train
Copied 2270 to train
Copied 3018 to train
Copied 2308 to train
Copied 334 to train
Copied 974 to train
Copied 195 to train
Copied 3035 to train
Copied 892 to train
Copied 1166 to train
Copied 922 to train